const GamesData = [
  { name: "Tung Sahur Horror", url: "https://lanyon-tutoring-help.github.io/tung-sahur-horror", category: "action", description: "Scary Horror challenge with Tung Tung Sahur." },
  { name: "Slope", url: "https://olivia-games.github.io/seraph/games/slope/index.html", category: "action", description: "Fast-paced action challenge featuring Slope." },
  { name: "Subway Surfers", url: "https://olivia-games.github.io/seraph/games/subwaysurfers/index.html", category: "action", description: "React quickly and survive intense action in Subwaysurfers." },
  { name: "Flappy", url: "https://olivia-games.github.io/seraph/games/flappy/index.html", category: "action", description: "Flappy delivers nonstop arcade-style action." },
  { name: "Papa's Pizzaria", url: "https://olivia-games.github.io/seraph/games/papaspizzaria/index.html", category: "restaurant", description: "Cook, serve, and manage customers in Papaspizzaria." },
  { name: "Papa's Burgeria", url: "https://olivia-games.github.io/seraph/games/papasburgeria/index.html", category: "restaurant", description: "Papasburgeria lets you run your own virtual restaurant." },
  { name: "Super Mario 64", url: "https://olivia-games.github.io/seraph/games/sm64/index.html", category: "action", description: "Sm64 delivers nonstop arcade-style action." },
  { name: "Run 3", url: "https://olivia-games.github.io/seraph/games/run3/index.html", category: "action", description: "Fast-paced action challenge featuring Run3." },
  { name: "Bitlife", url: "https://olivia-games.github.io/seraph/games/bitlife/index.html", category: "action", description: "React quickly and survive intense action in Bitlife." },
  { name: "Crossy Road", url: "https://olivia-games.github.io/seraph/games/crossy/index.html", category: "action", description: "Crossy delivers nonstop arcade-style action." },
  { name: "Minecraft", url: "https://olivia-games.github.io/seraph/games/mc/index.html", category: "action", description: "Fast-paced action challenge featuring Mc." },
  { name: "Cookie Clicker", url: "https://olivia-games.github.io/seraph/games/cookieclicker/index.html", category: "strategy", description: "Cookieclicker rewards smart decisions and strategy." },
  { name: "Temple Run 2", url: "https://olivia-games.github.io/seraph/games/templerun2/index.html", category: "action", description: "Templerun2 delivers nonstop arcade-style action." },
  { name: "Duck Life 4", url: "https://olivia-games.github.io/seraph/games/ducklife4/index.html", category: "action", description: "Fast-paced action challenge featuring Ducklife4." },
  { name: "Dino Game", url: "https://olivia-games.github.io/seraph/games/dinogame/index.html", category: "action", description: "React quickly and survive intense action in Dinogame." },
  { name: "Jetpack Joyride", url: "https://olivia-games.github.io/seraph/games/jetpackjoyride/index.html", category: "action", description: "Jetpackjoyride delivers nonstop arcade-style action." },
  { name: "Retro Bowl", url: "https://olivia-games.github.io/seraph/games/retrobowl/index.html", category: "action", description: "Fast-paced action challenge featuring Retrobowl." },
  { name: "Fruit Ninja", url: "https://olivia-games.github.io/seraph/games/fruitninja/index.html", category: "action", description: "React quickly and survive intense action in Fruitninja." },
  { name: "Doodle Jump", url: "https://olivia-games.github.io/seraph/games/doodlejump/index.html", category: "action", description: "Doodlejump delivers nonstop arcade-style action." },
  { name: "2048", url: "https://olivia-games.github.io/seraph/games/2048/index.html", category: "puzzle", description: "Solve clever puzzles and brain teasers in 2048." },
  { name: "Tetris", url: "https://olivia-games.github.io/seraph/games/tetris/index.html", category: "action", description: "React quickly and survive intense action in Tetris." },
  { name: "Fancy Pants Adventure", url: "https://olivia-games.github.io/seraph/games/fancypantsadventure/index.html", category: "action", description: "Fancypantsadventure delivers nonstop arcade-style action." },
  { name: "Happy Wheels", url: "https://olivia-games.github.io/seraph/games/happywheels/index.html", category: "action", description: "Fast-paced action challenge featuring Happywheels." },
  { name: "Papa's Hot Doggeria", url: "https://olivia-games.github.io/seraph/games/papashotdoggeria/index.html", category: "restaurant", description: "Papashotdoggeria lets you run your own virtual restaurant." },
  { name: "Paper.io 2", url: "https://olivia-games.github.io/seraph/games/paperio2/index.html", category: "action", description: "Paperio2 delivers nonstop arcade-style action." },
  { name: "Super Hot", url: "https://olivia-games.github.io/seraph/games/superhot/index.html", category: "action", description: "Fast-paced action challenge featuring Superhot." },
  { name: "The Binding of Isaac", url: "https://olivia-games.github.io/seraph/games/thebindingofisaac/index.html", category: "action", description: "React quickly and survive intense action in Thebindingofisaac." },
  { name: "Town Scaper", url: "https://olivia-games.github.io/seraph/games/townscaper/index.html", category: "action", description: "Townscaper delivers nonstop arcade-style action." },
  { name: "Tunnel Rush", url: "https://olivia-games.github.io/seraph/games/tunnelrush/index.html", category: "action", description: "Fast-paced action challenge featuring Tunnelrush." },
  { name: "Theme Hotel", url: "https://olivia-games.github.io/seraph/games/themehotel/index.html", category: "action", description: "React quickly and survive intense action in Themehotel." },
  { name: "Escaping the Prison", url: "https://olivia-games.github.io/seraph/games/escapingtheprison/index.html", category: "action", description: "Escapingtheprison delivers nonstop arcade-style action." },
  { name: "Stealing the Diamond", url: "https://olivia-games.github.io/seraph/games/stealingthediamond/index.html", category: "action", description: "Fast-paced action challenge featuring Stealingthediamond." },
  { name: "Infiltrating the Airship", url: "https://olivia-games.github.io/seraph/games/infiltratingtheairship/index.html", category: "action", description: "React quickly and survive intense action in Infiltratingtheairship." },
  { name: "Fleeing the Complex", url: "https://olivia-games.github.io/seraph/games/fleeingthecomplex/index.html", category: "action", description: "Fleeingthecomplex delivers nonstop arcade-style action." },
  { name: "The Impossible Quiz", url: "https://olivia-games.github.io/seraph/games/theimpossiblequiz/index.html", category: "action", description: "Fast-paced action challenge featuring Theimpossiblequiz." },
  { name: "Solitaire", url: "https://olivia-games.github.io/seraph/games/solitaire/index.html", category: "action", description: "React quickly and survive intense action in Solitaire." },
  { name: "Drift Hunters", url: "https://olivia-games.github.io/seraph/games/drifthunters/index.html", category: "racing", description: "Fast and competitive racing action in Drifthunters." },
  { name: "Vex 6", url: "https://olivia-games.github.io/seraph/games/vex6/index.html", category: "action", description: "Fast-paced action challenge featuring Vex6." },
  { name: "Among Us", url: "https://olivia-games.github.io/seraph/games/amongus/index.html", category: "action", description: "React quickly and survive intense action in Amongus." },
  { name: "Surf", url: "https://olivia-games.github.io/seraph/games/surf/index.html", category: "action", description: "Surf delivers nonstop arcade-style action." },
  { name: "Moto X3M", url: "https://23azostore.github.io/s8/moto-x3m", category: "racing", description: "Race at high speed and master the tracks in Motox3m." },
  { name: "FNAF", url: "https://olivia-games.github.io/seraph/games/fnaf/index.html", category: "horror", description: "Fnaf delivers suspense and horror elements." },
  { name: "FNAF 2", url: "https://olivia-games.github.io/seraph/games/fnaf-2/index.html", category: "horror", description: "Survive the fear and atmosphere of Fnaf 2." },
  { name: "FNAF 3", url: "https://olivia-games.github.io/seraph/games/fnaf-3/index.html", category: "horror", description: "A tense and scary experience awaits in Fnaf 3." },
  { name: "FNAF 4", url: "https://olivia-games.github.io/seraph/games/fnaf-4/index.html", category: "horror", description: "Fnaf 4 delivers suspense and horror elements." },
  { name: "Riddle School", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool1/index.html", category: "action", description: "Riddleschool delivers nonstop arcade-style action." },
  { name: "Riddle School 2", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool2/index.html", category: "action", description: "Fast-paced action challenge featuring Riddleschool." },
  { name: "Riddle School 3", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool3/index.html", category: "action", description: "React quickly and survive intense action in Riddleschool." },
  { name: "Riddle School 4", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool4/index.html", category: "action", description: "Riddleschool delivers nonstop arcade-style action." },
  { name: "Riddle School 5", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool5/index.html", category: "action", description: "Fast-paced action challenge featuring Riddleschool." },
  { name: "Riddle School Transfer", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddletransfer/index.html", category: "action", description: "React quickly and survive intense action in Riddleschool." },
  { name: "Riddle School Transfer 2", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddletransfer2/index.html", category: "action", description: "Riddleschool delivers nonstop arcade-style action." },
  { name: "Drift Boss", url: "https://olivia-games.github.io/seraph/games/driftboss/index.html", category: "racing", description: "Race at high speed and master the tracks in Driftboss." },
  { name: "FNF", url: "https://olivia-games.github.io/seraph/games/fnf/index.html", category: "music", description: "Fnf combines music with fast-paced gameplay." },
  { name: "Pac-Man", url: "https://olivia-games.github.io/seraph/games/pacman/index.html", category: "action", description: "Pacman delivers nonstop arcade-style action." },
  { name: "Papa's Pancakeria", url: "https://olivia-games.github.io/seraph/games/papaspancakeria/index.html", category: "restaurant", description: "Cook, serve, and manage customers in Papaspancakeria." },
  { name: "Rooftop", url: "https://olivia-games.github.io/seraph/games/rooftop/index.html", category: "action", description: "React quickly and survive intense action in Rooftop." },
  { name: "Baldi's Basics", url: "https://olivia-games.github.io/seraph/games/baldisbasics/index.html", category: "action", description: "Baldisbasics delivers nonstop arcade-style action." },
  { name: "Bob the Robber 2", url: "https://olivia-games.github.io/seraph/games/bobtherobber2/index.html", category: "action", description: "Fast-paced action challenge featuring Bobtherobber2." },
  { name: "Minesweeper", url: "https://olivia-games.github.io/seraph/games/minesweeper/index.html", category: "puzzle", description: "Minesweeper challenges logic and problem-solving skills." },
  { name: "Pokemon Emerald", url: "https://olivia-games.github.io/seraph/games/pokemonemerald/index.html", category: "rpg", description: "An RPG adventure filled with depth: Pokemonemerald." },
  { name: "Pokemon Fire Red", url: "https://olivia-games.github.io/seraph/games/pokemonfirered/index.html", category: "rpg", description: "Embark on an epic role-playing journey in Pokemonfirered." },
  { name: "Super Mario Bros", url: "https://olivia-games.github.io/seraph/games/supermariobros/index.html", category: "platformer", description: "Supermariobros challenges your timing and movement skills." },
  { name: "Super Mario Kart", url: "https://olivia-games.github.io/seraph/games/supermariokart/index.html", category: "platformer", description: "A skill-based platforming adventure called Supermariokart." },
  { name: "Super Mario World", url: "https://olivia-games.github.io/seraph/games/supermarioworld/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Supermarioworld." },
  { name: "There Is No Game", url: "https://olivia-games.github.io/seraph/games/thereisnogame/index.html", category: "action", description: "React quickly and survive intense action in Thereisnogame." },
  { name: "World's Hardest Game", url: "https://olivia-games.github.io/seraph/games/worldshardestgame/index.html", category: "action", description: "Worldshardestgame delivers nonstop arcade-style action." },
  { name: "Castlevania", url: "https://olivia-games.github.io/seraph/games/castlevania/index.html", category: "action", description: "Fast-paced action challenge featuring Castlevania." },
  { name: "Donkey Kong", url: "https://olivia-games.github.io/seraph/games/donkeykong/index.html", category: "action", description: "React quickly and survive intense action in Donkeykong." },
  { name: "Dr. Mario", url: "https://olivia-games.github.io/seraph/games/drmario/index.html", category: "platformer", description: "A skill-based platforming adventure called Drmario." },
  { name: "Metroid", url: "https://olivia-games.github.io/seraph/games/metroid/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Metroid." },
  { name: "Super Mario Bros 2", url: "https://olivia-games.github.io/seraph/games/supermariobros2/index.html", category: "platformer", description: "Supermariobros2 challenges your timing and movement skills." },
  { name: "Super Mario Bros 3", url: "https://olivia-games.github.io/seraph/games/supermariobros3/index.html", category: "platformer", description: "A skill-based platforming adventure called Supermariobros3." },
  { name: "The Legend of Zelda", url: "https://olivia-games.github.io/seraph/games/thelegendofzelda/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Thelegendofzelda." },
  { name: "Wario Ware", url: "https://olivia-games.github.io/seraph/games/warioware/index.html", category: "action", description: "React quickly and survive intense action in Warioware." },
  { name: "Yoshi's Island", url: "https://olivia-games.github.io/seraph/games/yoshisisland/index.html", category: "action", description: "Yoshisisland delivers nonstop arcade-style action." },
  { name: "Donkey Kong Land", url: "https://olivia-games.github.io/seraph/games/donkeykongland/index.html", category: "action", description: "Fast-paced action challenge featuring Donkeykongland." },
  { name: "Kirby's Dream Land", url: "https://olivia-games.github.io/seraph/games/kirbysdreamland/index.html", category: "platformer", description: "Kirbysdreamland challenges your timing and movement skills." },
  { name: "Super Mario Land", url: "https://olivia-games.github.io/seraph/games/supermarioland/index.html", category: "platformer", description: "A skill-based platforming adventure called Supermarioland." },
  { name: "Doge Miner", url: "https://olivia-games.github.io/seraph/games/dogeminer/index.html", category: "action", description: "Fast-paced action challenge featuring Dogeminer." },
  { name: "Tanuki Sunset", url: "https://olivia-games.github.io/seraph/games/tanukisunset/index.html", category: "action", description: "React quickly and survive intense action in Tanukisunset." },
  { name: "Aquapark Slides", url: "https://olivia-games.github.io/seraph/games/aquaparkslides/index.html", category: "action", description: "Aquaparkslides delivers nonstop arcade-style action." },
  { name: "Color Switch", url: "https://olivia-games.github.io/seraph/games/colorswitch/index.html", category: "action", description: "Fast-paced action challenge featuring Colorswitch." },
  { name: "Papa's Freezeria", url: "https://olivia-games.github.io/seraph/games/papasfreezeria/index.html", category: "restaurant", description: "Papasfreezeria lets you run your own virtual restaurant." },
  { name: "BTD", url: "https://olivia-games.github.io/seraph/games/btd/btd/index.html", category: "strategy", description: "A strategic gameplay experience built around Btd." },
  { name: "BTD 2", url: "https://olivia-games.github.io/seraph/games/btd/btd2/index.html", category: "strategy", description: "Plan ahead and outthink opponents in Btd." },
  { name: "BTD 3", url: "https://olivia-games.github.io/seraph/games/btd/btd3/index.html", category: "strategy", description: "Btd rewards smart decisions and strategy." },
  { name: "BTD 4", url: "https://olivia-games.github.io/seraph/games/btd/btd4/index.html", category: "strategy", description: "A strategic gameplay experience built around Btd." },
  { name: "Bomberman", url: "https://olivia-games.github.io/seraph/games/bomberman/index.html", category: "action", description: "Fast-paced action challenge featuring Bomberman." },
  { name: "Fire Emblem", url: "https://olivia-games.github.io/seraph/games/fireemblem/index.html", category: "action", description: "React quickly and survive intense action in Fireemblem." },
  { name: "Ice Climber", url: "https://olivia-games.github.io/seraph/games/iceclimber/index.html", category: "action", description: "Iceclimber delivers nonstop arcade-style action." },
  { name: "Mario Kart Super Circuit", url: "https://olivia-games.github.io/seraph/games/mariokartsupercircuit/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Mariokartsupercircuit." },
  { name: "Pokemon Leaf Green", url: "https://olivia-games.github.io/seraph/games/pokemonleafgreen/index.html", category: "rpg", description: "Pokemonleafgreen features progression, exploration, and story." },
  { name: "Pokemon Ruby", url: "https://olivia-games.github.io/seraph/games/pokemonruby/index.html", category: "rpg", description: "An RPG adventure filled with depth: Pokemonruby." },
  { name: "Pokemon Sapphire", url: "https://olivia-games.github.io/seraph/games/pokemonsapphire/index.html", category: "rpg", description: "Embark on an epic role-playing journey in Pokemonsapphire." },
  { name: "Superstar Saga", url: "https://olivia-games.github.io/seraph/games/superstarsaga/index.html", category: "action", description: "React quickly and survive intense action in Superstarsaga." },
  { name: "A Dance of Fire and Ice", url: "https://olivia-games.github.io/seraph/games/adofai/index.html", category: "action", description: "Adofai delivers nonstop arcade-style action." },
  { name: "Super Smash Flash", url: "https://olivia-games.github.io/seraph/games/supersmashflash/index.html", category: "fighting", description: "Battle opponents in skill-based combat in Supersmashflash." },
  { name: "Super Meat Boy", url: "https://olivia-games.github.io/seraph/games/supermeatboy/index.html", category: "action", description: "React quickly and survive intense action in Supermeatboy." },
  { name: "Stickman Hook", url: "https://olivia-games.github.io/seraph/games/stickmanhook/index.html", category: "action", description: "Stickmanhook delivers nonstop arcade-style action." },
  { name: "Defend the Tank", url: "https://olivia-games.github.io/seraph/games/defendthetank/index.html", category: "action", description: "Fast-paced action challenge featuring Defendthetank." },
  { name: "Sort the Court", url: "https://olivia-games.github.io/seraph/games/sortthecourt/index.html", category: "action", description: "React quickly and survive intense action in Sortthecourt." },
  { name: "This Is the Only Level", url: "https://olivia-games.github.io/seraph/games/thisistheonlylevel/index.html", category: "action", description: "Thisistheonlylevel delivers nonstop arcade-style action." },
  { name: "Run", url: "https://olivia-games.github.io/seraph/games/run/index.html", category: "action", description: "Fast-paced action challenge featuring Run." },
  { name: "Run 2", url: "https://olivia-games.github.io/seraph/games/run2/index.html", category: "action", description: "React quickly and survive intense action in Run2." },
  { name: "Battleships", url: "https://olivia-games.github.io/seraph/games/battleships/index.html", category: "action", description: "Battleships delivers nonstop arcade-style action." },
  { name: "Breaking the Bank", url: "https://olivia-games.github.io/seraph/games/breakingthebank/index.html", category: "action", description: "Fast-paced action challenge featuring Breakingthebank." },
  { name: "Duck Life", url: "https://olivia-games.github.io/seraph/games/ducklife/index.html", category: "action", description: "React quickly and survive intense action in Ducklife." },
  { name: "Duck Life 2", url: "https://olivia-games.github.io/seraph/games/ducklife2/index.html", category: "action", description: "Ducklife2 delivers nonstop arcade-style action." },
  { name: "Duck Life 3", url: "https://olivia-games.github.io/seraph/games/ducklife3/index.html", category: "action", description: "Fast-paced action challenge featuring Ducklife3." },
  { name: "Line Rider", url: "https://olivia-games.github.io/seraph/games/linerider/index.html", category: "action", description: "React quickly and survive intense action in Linerider." },
  { name: "Mario Combat", url: "https://olivia-games.github.io/seraph/games/mariocombat/index.html", category: "platformer", description: "A skill-based platforming adventure called Mariocombat." },
  { name: "Raft Wars 2", url: "https://olivia-games.github.io/seraph/games/raftwars2/index.html", category: "action", description: "Fast-paced action challenge featuring Raftwars2." },
  { name: "Space Invaders", url: "https://olivia-games.github.io/seraph/games/spaceinvaders/index.html", category: "action", description: "React quickly and survive intense action in Spaceinvaders." },
  { name: "Animal Crossing: Wild World", url: "https://olivia-games.github.io/seraph/games/animalcrossingwildworld/index.html", category: "action", description: "Animalcrossingwildworld delivers nonstop arcade-style action." },
  { name: "Mario Kart DS", url: "https://olivia-games.github.io/seraph/games/mariokartds/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Mariokartds." },
  { name: "New Super Mario Bros", url: "https://olivia-games.github.io/seraph/games/newsupermariobros/index.html", category: "platformer", description: "Newsupermariobros challenges your timing and movement skills." },
  { name: "Nintendogs", url: "https://olivia-games.github.io/seraph/games/nintendogs/index.html", category: "action", description: "Nintendogs delivers nonstop arcade-style action." },
  { name: "Super Mario 64 DS", url: "https://olivia-games.github.io/seraph/games/sm64ds/index.html", category: "action", description: "Fast-paced action challenge featuring Sm64ds." },
  { name: "Gun Mayhem", url: "https://olivia-games.github.io/seraph/games/gunmayhem/index.html", category: "action", description: "React quickly and survive intense action in Gunmayhem." },
  { name: "Learn to Fly", url: "https://olivia-games.github.io/seraph/games/learntofly/index.html", category: "action", description: "Learntofly delivers nonstop arcade-style action." },
  { name: "Rooftop 2", url: "https://olivia-games.github.io/seraph/games/rooftop2/index.html", category: "action", description: "Fast-paced action challenge featuring Rooftop2." },
  { name: "Fireboy and Watergirl", url: "https://olivia-games.github.io/seraph/games/fireboywatergirl/index.html", category: "action", description: "React quickly and survive intense action in Fireboywatergirl." },
  { name: "Chibi Knight", url: "https://olivia-games.github.io/seraph/games/chibiknight/index.html", category: "action", description: "Chibiknight delivers nonstop arcade-style action." },
  { name: "Cluster Rush", url: "https://olivia-games.github.io/seraph/games/clusterrush/index.html", category: "action", description: "Fast-paced action challenge featuring Clusterrush." },
  { name: "Doodle Defender", url: "https://olivia-games.github.io/seraph/games/doodledefender/index.html", category: "action", description: "React quickly and survive intense action in Doodledefender." },
  { name: "Learn to Fly 2", url: "https://olivia-games.github.io/seraph/games/learntofly2/index.html", category: "action", description: "Learntofly2 delivers nonstop arcade-style action." },
  { name: "Papa's Scooperia", url: "https://olivia-games.github.io/seraph/games/papasscooperia/index.html", category: "restaurant", description: "Cook, serve, and manage customers in Papasscooperia." },
  { name: "Papa's Sushiria", url: "https://olivia-games.github.io/seraph/games/papassushiria/index.html", category: "restaurant", description: "Papassushiria lets you run your own virtual restaurant." },
  { name: "Papa's Wingeria", url: "https://olivia-games.github.io/seraph/games/papaswingeria/index.html", category: "restaurant", description: "Prepare meals and satisfy customers in Papaswingeria." },
  { name: "Raft Wars", url: "https://olivia-games.github.io/seraph/games/raftwars/index.html", category: "action", description: "Fast-paced action challenge featuring Raftwars." },
  { name: "Unfair Mario", url: "https://olivia-games.github.io/seraph/games/unfairmario/index.html", category: "platformer", description: "Unfairmario challenges your timing and movement skills." },
  { name: "Boxing Physics 2", url: "https://olivia-games.github.io/seraph/games/boxingphysics2/index.html", category: "fighting", description: "Test your reflexes and combos in Boxingphysics2." },
  { name: "Ace Attorney", url: "https://olivia-games.github.io/seraph/games/aceattorney/index.html", category: "action", description: "Fast-paced action challenge featuring Aceattorney." },
  { name: "Metal Gear Solid", url: "https://olivia-games.github.io/seraph/games/metalgearsolid/index.html", category: "action", description: "React quickly and survive intense action in Metalgearsolid." },
  { name: "Mother 3", url: "https://olivia-games.github.io/seraph/games/mother3/index.html", category: "action", description: "Mother3 delivers nonstop arcade-style action." },
  { name: "Pokemon Diamond", url: "https://olivia-games.github.io/seraph/games/pokemondiamond/index.html", category: "rpg", description: "Embark on an epic role-playing journey in Pokemondiamond." },
  { name: "Pokemon Platinum", url: "https://olivia-games.github.io/seraph/games/pokemonplatinum/index.html", category: "rpg", description: "Pokemonplatinum features progression, exploration, and story." },
  { name: "Pokemon Soul Silver", url: "https://olivia-games.github.io/seraph/games/pokemonsoulsilver/index.html", category: "rpg", description: "An RPG adventure filled with depth: Pokemonsoulsilver." },
  { name: "Advance Wars", url: "https://olivia-games.github.io/seraph/games/advancewars/index.html", category: "action", description: "Fast-paced action challenge featuring Advancewars." },
  { name: "Banjo Pilot", url: "https://olivia-games.github.io/seraph/games/banjopilot/index.html", category: "action", description: "React quickly and survive intense action in Banjopilot." },
  { name: "Super Monkey Ball Jr.", url: "https://olivia-games.github.io/seraph/games/supermonkeyballjr/index.html", category: "action", description: "Supermonkeyballjr delivers nonstop arcade-style action." },
  { name: "The Impossible Quiz 2", url: "https://olivia-games.github.io/seraph/games/theimpossiblequiz2/index.html", category: "action", description: "Fast-paced action challenge featuring Theimpossiblequiz2." },
  { name: "Papa's Donuteria", url: "https://olivia-games.github.io/seraph/games/papasdonuteria/index.html", category: "restaurant", description: "Papasdonuteria lets you run your own virtual restaurant." },
  { name: "Fancy Pants Adventure 2", url: "https://olivia-games.github.io/seraph/games/fancypantsadventure2/index.html", category: "action", description: "Fancypantsadventure2 delivers nonstop arcade-style action." },
  { name: "Tiny Fishing", url: "https://olivia-games.github.io/seraph/games/tinyfishing/index.html", category: "action", description: "Fast-paced action challenge featuring Tinyfishing." },
  { name: "Big Red Button", url: "https://olivia-games.github.io/seraph/games/bigredbutton/index.html", category: "action", description: "React quickly and survive intense action in Bigredbutton." },
  { name: "Achievement Unlocked", url: "https://olivia-games.github.io/seraph/games/achievementunlocked/index.html", category: "action", description: "Achievementunlocked delivers nonstop arcade-style action." },
  { name: "Kirby Mass Attack", url: "https://olivia-games.github.io/seraph/games/kirbymassattack/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Kirbymassattack." },
  { name: "Sonic Advance", url: "https://olivia-games.github.io/seraph/games/sonicadvance/index.html", category: "platformer", description: "Sonicadvance challenges your timing and movement skills." },
  { name: "Worms World Party", url: "https://olivia-games.github.io/seraph/games/wormsworldparty/index.html", category: "action", description: "Wormsworldparty delivers nonstop arcade-style action." },
  { name: "Bad Ice Cream", url: "https://olivia-games.github.io/seraph/games/badicecream/index.html", category: "action", description: "Fast-paced action challenge featuring Badicecream." },
  { name: "Bad Ice Cream 2", url: "https://olivia-games.github.io/seraph/games/badicecream2/index.html", category: "action", description: "React quickly and survive intense action in Badicecream2." },
  { name: "Bad Ice Cream 3", url: "https://olivia-games.github.io/seraph/games/badicecream3/index.html", category: "action", description: "Badicecream3 delivers nonstop arcade-style action." },
  { name: "Adventure Capitalist", url: "https://olivia-games.github.io/seraph/games/adventurecapitalist/index.html", category: "action", description: "Fast-paced action challenge featuring Adventurecapitalist." },
  { name: "Monkey Mart", url: "https://olivia-games.github.io/seraph/games/monkeymart/index.html", category: "action", description: "React quickly and survive intense action in Monkeymart." },
  { name: "Doom 64", url: "https://olivia-games.github.io/seraph/games/doom64/index.html", category: "action", description: "Doom64 delivers nonstop arcade-style action." },
  { name: "Banjo-Kazooie", url: "https://olivia-games.github.io/seraph/games/banjokazooie/index.html", category: "action", description: "Fast-paced action challenge featuring Banjokazooie." },
  { name: "Donkey Kong 64", url: "https://olivia-games.github.io/seraph/games/donkeykong64/index.html", category: "action", description: "React quickly and survive intense action in Donkeykong64." },
  { name: "F-Zero X", url: "https://olivia-games.github.io/seraph/games/fzerox/index.html", category: "action", description: "Fzerox delivers nonstop arcade-style action." },
  { name: "Kirby 64", url: "https://olivia-games.github.io/seraph/games/kirby64/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Kirby64." },
  { name: "Mario Kart 64", url: "https://olivia-games.github.io/seraph/games/mariokart64/index.html", category: "platformer", description: "Mariokart64 challenges your timing and movement skills." },
  { name: "Mario Party", url: "https://olivia-games.github.io/seraph/games/marioparty/index.html", category: "platformer", description: "A skill-based platforming adventure called Marioparty." },
  { name: "Mario Party 2", url: "https://olivia-games.github.io/seraph/games/marioparty2/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Marioparty2." },
  { name: "Ocarina of Time", url: "https://olivia-games.github.io/seraph/games/ocarinaoftime/index.html", category: "action", description: "React quickly and survive intense action in Ocarinaoftime." },
  { name: "Star Fox 64", url: "https://olivia-games.github.io/seraph/games/starfox64/index.html", category: "action", description: "Starfox64 delivers nonstop arcade-style action." },
  { name: "Super Smash Bros", url: "https://olivia-games.github.io/seraph/games/supersmashbros/index.html", category: "fighting", description: "Battle opponents in skill-based combat in Supersmashbros." },
  { name: "Street Fighter 2", url: "https://olivia-games.github.io/seraph/games/streetfighter2/index.html", category: "fighting", description: "Streetfighter2 focuses on fast and competitive fighting." },
  { name: "Getaway Shootout", url: "https://olivia-games.github.io/seraph/games/getawayshootout/index.html", category: "action", description: "Getawayshootout delivers nonstop arcade-style action." },
  { name: "Rabbit Samurai", url: "https://olivia-games.github.io/seraph/games/rabbitsamurai/index.html", category: "action", description: "Fast-paced action challenge featuring Rabbitsamurai." },
  { name: "Mario Party DS", url: "https://olivia-games.github.io/seraph/games/mariopartyds/index.html", category: "platformer", description: "Mariopartyds challenges your timing and movement skills." },
  { name: "Professor Layton", url: "https://olivia-games.github.io/seraph/games/professorlayton/index.html", category: "action", description: "Professorlayton delivers nonstop arcade-style action." },
  { name: "Scribblenauts", url: "https://olivia-games.github.io/seraph/games/scribblenauts/index.html", category: "action", description: "Fast-paced action challenge featuring Scribblenauts." },
  { name: "Advance Wars 2", url: "https://olivia-games.github.io/seraph/games/advancewars2/index.html", category: "action", description: "React quickly and survive intense action in Advancewars2." },
  { name: "Harvest Moon", url: "https://olivia-games.github.io/seraph/games/harvestmoon/index.html", category: "action", description: "Harvestmoon delivers nonstop arcade-style action." },
  { name: "Mario Tennis", url: "https://olivia-games.github.io/seraph/games/mariotennis/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Mariotennis." },
  { name: "Mega Man Zero", url: "https://olivia-games.github.io/seraph/games/megamanzero/index.html", category: "action", description: "React quickly and survive intense action in Megamanzero." },
  { name: "Pokemon Mystery Dungeon", url: "https://olivia-games.github.io/seraph/games/pokemonmysterydungeon/index.html", category: "rpg", description: "An RPG adventure filled with depth: Pokemonmysterydungeon." },
  { name: "Pokemon Unbound", url: "https://olivia-games.github.io/seraph/games/pokemonunbound/index.html", category: "rpg", description: "Embark on an epic role-playing journey in Pokemonunbound." },
  { name: "Papa's Cheeseria", url: "https://olivia-games.github.io/seraph/games/papascheeseria/index.html", category: "restaurant", description: "Papascheeseria lets you run your own virtual restaurant." },
  { name: "Papa's Cupcakeria", url: "https://olivia-games.github.io/seraph/games/papascupcakeria/index.html", category: "restaurant", description: "Prepare meals and satisfy customers in Papascupcakeria." },
  { name: "Papa's Bakeria", url: "https://olivia-games.github.io/seraph/games/papasbakeria/index.html", category: "restaurant", description: "Cook, serve, and manage customers in Papasbakeria." },
  { name: "Papa's Pastaria", url: "https://olivia-games.github.io/seraph/games/papaspastaria/index.html", category: "restaurant", description: "Papaspastaria lets you run your own virtual restaurant." },
  { name: "Gun Mayhem 2", url: "https://olivia-games.github.io/seraph/games/gunmayhem2/index.html", category: "action", description: "Gunmayhem2 delivers nonstop arcade-style action." },
  { name: "Gun Mayhem Redux", url: "https://olivia-games.github.io/seraph/games/gunmayhemredux/index.html", category: "action", description: "Fast-paced action challenge featuring Gunmayhemredux." },
  { name: "Achievement Unlocked 2", url: "https://olivia-games.github.io/seraph/games/achievementunlocked2/index.html", category: "action", description: "React quickly and survive intense action in Achievementunlocked2." },
  { name: "Achievement Unlocked 3", url: "https://olivia-games.github.io/seraph/games/achievementunlocked3/index.html", category: "action", description: "Achievementunlocked3 delivers nonstop arcade-style action." },
  { name: "Factory Balls", url: "https://olivia-games.github.io/seraph/games/factoryballs/index.html", category: "action", description: "Fast-paced action challenge featuring Factoryballs." },
  { name: "Skywire", url: "https://olivia-games.github.io/seraph/games/skywire/index.html", category: "action", description: "React quickly and survive intense action in Skywire." },
  { name: "Super Mario Flash", url: "https://olivia-games.github.io/seraph/games/supermarioflash/index.html", category: "platformer", description: "A skill-based platforming adventure called Supermarioflash." },
  { name: "Golden Sun", url: "https://olivia-games.github.io/seraph/games/goldensun/index.html", category: "action", description: "Fast-paced action challenge featuring Goldensun." },
  { name: "Metroid Fusion", url: "https://olivia-games.github.io/seraph/games/metroidfusion/index.html", category: "platformer", description: "Metroidfusion challenges your timing and movement skills." },
  { name: "DBZ Supersonic Warriors", url: "https://olivia-games.github.io/seraph/games/dbzsupersonicwarriors/index.html", category: "platformer", description: "A skill-based platforming adventure called Dbzsupersonicwarriors." },
  { name: "Wario Land 4", url: "https://olivia-games.github.io/seraph/games/warioland4/index.html", category: "action", description: "Fast-paced action challenge featuring Warioland4." },
  { name: "Duck Life 5", url: "https://olivia-games.github.io/seraph/games/ducklife5/index.html", category: "action", description: "React quickly and survive intense action in Ducklife5." },
  { name: "Learn to Fly 3", url: "https://olivia-games.github.io/seraph/games/learntofly3/index.html", category: "action", description: "Learntofly3 delivers nonstop arcade-style action." },
  { name: "Bloxors", url: "https://olivia-games.github.io/seraph/games/bloxors/index.html", category: "action", description: "Fast-paced action challenge featuring Bloxors." },
  { name: "Electric Man 2", url: "https://olivia-games.github.io/seraph/games/electricman2/index.html", category: "action", description: "React quickly and survive intense action in Electricman2." },
  { name: "Portal", url: "https://olivia-games.github.io/seraph/games/portal/index.html", category: "action", description: "Portal delivers nonstop arcade-style action." },
  { name: "Portal 2", url: "https://olivia-games.github.io/seraph/games/portal2/index.html", category: "action", description: "Fast-paced action challenge featuring Portal2." },
  { name: "Skywire 2", url: "https://olivia-games.github.io/seraph/games/skywire2/index.html", category: "action", description: "React quickly and survive intense action in Skywire2." },
  { name: "Duck Life 6", url: "https://olivia-games.github.io/seraph/games/ducklife6/index.html", category: "action", description: "Ducklife6 delivers nonstop arcade-style action." },
  { name: "Boxing Random", url: "https://olivia-games.github.io/seraph/games/boxingrandom/index.html", category: "fighting", description: "Battle opponents in skill-based combat in Boxingrandom." },
  { name: "Cell Machine", url: "https://olivia-games.github.io/seraph/games/cellmachine/index.html", category: "action", description: "React quickly and survive intense action in Cellmachine." },
  { name: "Stickman Boost", url: "https://olivia-games.github.io/seraph/games/stickmanboost/index.html", category: "action", description: "Stickmanboost delivers nonstop arcade-style action." },
  { name: "Vex 3", url: "https://olivia-games.github.io/seraph/games/vex3/index.html", category: "action", description: "Fast-paced action challenge featuring Vex3." },
  { name: "Vex 4", url: "https://olivia-games.github.io/seraph/games/vex4/index.html", category: "action", description: "React quickly and survive intense action in Vex4." },
  { name: "Skibidi 1v100", url: "https://olivia-games.github.io/seraph/games/skibidi1v100/index.html", category: "action", description: "Skibidi1v100 delivers nonstop arcade-style action." },
  { name: "GoldenEye 007", url: "https://olivia-games.github.io/seraph/games/goldeneye007/index.html", category: "action", description: "Fast-paced action challenge featuring Goldeneye007." },
  { name: "Majora's Mask", url: "https://olivia-games.github.io/seraph/games/majorasmask/index.html", category: "action", description: "React quickly and survive intense action in Majorasmask." },
  { name: "Paper Mario", url: "https://olivia-games.github.io/seraph/games/papermario/index.html", category: "platformer", description: "A skill-based platforming adventure called Papermario." },
  { name: "Mario Golf", url: "https://olivia-games.github.io/seraph/games/mariogolf/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Mariogolf." },
  { name: "Pokemon Stadium", url: "https://olivia-games.github.io/seraph/games/pokemonstadium/index.html", category: "rpg", description: "Pokemonstadium features progression, exploration, and story." },
  { name: "Excitebike 64", url: "https://olivia-games.github.io/seraph/games/excitebike64/index.html", category: "action", description: "Excitebike64 delivers nonstop arcade-style action." },
  { name: "Pokemon Snap", url: "https://olivia-games.github.io/seraph/games/pokemonsnap/index.html", category: "rpg", description: "Embark on an epic role-playing journey in Pokemonsnap." },
  { name: "Mario Party 3", url: "https://olivia-games.github.io/seraph/games/marioparty3/index.html", category: "platformer", description: "Marioparty3 challenges your timing and movement skills." },
  { name: "Sonic Advance 2", url: "https://olivia-games.github.io/seraph/games/sonicadvance2/index.html", category: "platformer", description: "A skill-based platforming adventure called Sonicadvance2." },
  { name: "Bowser's Inside Story", url: "https://olivia-games.github.io/seraph/games/bowsersinsidestory/index.html", category: "action", description: "Fast-paced action challenge featuring Bowsersinsidestory." },
  { name: "Spirit Tracks", url: "https://olivia-games.github.io/seraph/games/spirittracks/index.html", category: "action", description: "React quickly and survive intense action in Spirittracks." },
  { name: "The Sims 2", url: "https://olivia-games.github.io/seraph/games/thesims2/index.html", category: "action", description: "Thesims2 delivers nonstop arcade-style action." },
  { name: "Tetris DS", url: "https://olivia-games.github.io/seraph/games/tetrisds/index.html", category: "action", description: "Fast-paced action challenge featuring Tetrisds." },
  { name: "Sonic Rush", url: "https://olivia-games.github.io/seraph/games/sonicrush/index.html", category: "platformer", description: "Sonicrush challenges your timing and movement skills." },
  { name: "The Sims 3", url: "https://olivia-games.github.io/seraph/games/thesims3/index.html", category: "action", description: "Thesims3 delivers nonstop arcade-style action." },
  { name: "Super Princess Peach", url: "https://olivia-games.github.io/seraph/games/superprincesspeach/index.html", category: "action", description: "Fast-paced action challenge featuring Superprincesspeach." },
  { name: "Lego Batman", url: "https://olivia-games.github.io/seraph/games/legobatman/index.html", category: "action", description: "React quickly and survive intense action in Legobatman." },
  { name: "Doom 2", url: "https://olivia-games.github.io/seraph/games/doom2/index.html", category: "action", description: "Doom2 delivers nonstop arcade-style action." },
  { name: "Duke Nukem Advance", url: "https://olivia-games.github.io/seraph/games/dukenukemadvance/index.html", category: "action", description: "Fast-paced action challenge featuring Dukenukemadvance." },
  { name: "Mario Party Advance", url: "https://olivia-games.github.io/seraph/games/mariopartyadvance/index.html", category: "platformer", description: "Mariopartyadvance challenges your timing and movement skills." },
  { name: "Mario Pinball Land", url: "https://olivia-games.github.io/seraph/games/mariopinballland/index.html", category: "platformer", description: "A skill-based platforming adventure called Mariopinballland." },
  { name: "Pac-Man World", url: "https://olivia-games.github.io/seraph/games/pacmanworld/index.html", category: "action", description: "Fast-paced action challenge featuring Pacmanworld." },
  { name: "Rayman 3", url: "https://olivia-games.github.io/seraph/games/rayman3/index.html", category: "action", description: "React quickly and survive intense action in Rayman3." },
  { name: "Shrek 2", url: "https://olivia-games.github.io/seraph/games/shrek2/index.html", category: "action", description: "Shrek2 delivers nonstop arcade-style action." },
  { name: "SimCity", url: "https://olivia-games.github.io/seraph/games/simcity/index.html", category: "action", description: "Fast-paced action challenge featuring Simcity." },
  { name: "Simpsons Road Rage", url: "https://olivia-games.github.io/seraph/games/simpsonsroadrage/index.html", category: "action", description: "React quickly and survive intense action in Simpsonsroadrage." },
  { name: "Diddy Kong Racing", url: "https://olivia-games.github.io/seraph/games/diddykongracing/index.html", category: "racing", description: "Fast and competitive racing action in Diddykongracing." },
  { name: "Wave Race 64", url: "https://olivia-games.github.io/seraph/games/waverace64/index.html", category: "action", description: "Fast-paced action challenge featuring Waverace64." },
  { name: "Quest 64", url: "https://olivia-games.github.io/seraph/games/quest64/index.html", category: "action", description: "React quickly and survive intense action in Quest64." },
  { name: "Gex 64", url: "https://olivia-games.github.io/seraph/games/gex64/index.html", category: "action", description: "Gex64 delivers nonstop arcade-style action." },
  { name: "Duke Nukem 64", url: "https://olivia-games.github.io/seraph/games/dukenukem64/index.html", category: "action", description: "Fast-paced action challenge featuring Dukenukem64." },
  { name: "Mortal Kombat 4", url: "https://olivia-games.github.io/seraph/games/mortalkombat4/index.html", category: "action", description: "React quickly and survive intense action in Mortalkombat4." },
  { name: "Bad Piggies", url: "https://olivia-games.github.io/seraph/games/badpiggies/index.html", category: "action", description: "Badpiggies delivers nonstop arcade-style action." },
  { name: "Super Mario Flash 2", url: "https://olivia-games.github.io/seraph/games/supermarioflash2/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Supermarioflash2." },
  { name: "Swords and Sandals", url: "https://olivia-games.github.io/seraph/games/swordsandsandals/index.html", category: "action", description: "React quickly and survive intense action in Swordsandsandals." },
  { name: "Swords and Sandals 2", url: "https://olivia-games.github.io/seraph/games/swordsandsandals2/index.html", category: "action", description: "Swordsandsandals2 delivers nonstop arcade-style action." },
  { name: "Wordle", url: "https://olivia-games.github.io/seraph/games/wordle/index.html", category: "puzzle", description: "Solve clever puzzles and brain teasers in Wordle." },
  { name: "Vex", url: "https://olivia-games.github.io/seraph/games/vex/index.html", category: "action", description: "React quickly and survive intense action in Vex." },
  { name: "Vex 2", url: "https://olivia-games.github.io/seraph/games/vex2/index.html", category: "action", description: "Vex2 delivers nonstop arcade-style action." },
  { name: "Vex 5", url: "https://olivia-games.github.io/seraph/games/vex5/index.html", category: "action", description: "Fast-paced action challenge featuring Vex5." },
  { name: "Vex 7", url: "https://olivia-games.github.io/seraph/games/vex7/index.html", category: "action", description: "React quickly and survive intense action in Vex7." },
  { name: "Stack", url: "https://olivia-games.github.io/seraph/games/stack/index.html", category: "action", description: "Stack delivers nonstop arcade-style action." },
  { name: "Skibidi Toilet Attack", url: "https://olivia-games.github.io/seraph/games/skibiditoiletattack/index.html", category: "action", description: "Fast-paced action challenge featuring Skibiditoiletattack." },
  { name: "Moto X3M Pool", url: "https://olivia-games.github.io/seraph/games/motox3mpool/index.html", category: "racing", description: "Motox3mpool puts your driving skills to the test." },
  { name: "Offline Paradise", url: "https://olivia-games.github.io/seraph/games/offlineparadise/index.html", category: "action", description: "Offlineparadise delivers nonstop arcade-style action." },
  { name: "A Link to the Past", url: "https://olivia-games.github.io/seraph/games/linktothepast/index.html", category: "action", description: "Fast-paced action challenge featuring Linktothepast." },
  { name: "Donkey Kong Country", url: "https://olivia-games.github.io/seraph/games/donkeykongcountry/index.html", category: "action", description: "React quickly and survive intense action in Donkeykongcountry." },
  { name: "Donkey Kong Country 2", url: "https://olivia-games.github.io/seraph/games/donkeykongcountry2/index.html", category: "action", description: "Donkeykongcountry2 delivers nonstop arcade-style action." },
  { name: "Super Bomberman", url: "https://olivia-games.github.io/seraph/games/superbomberman/index.html", category: "action", description: "Fast-paced action challenge featuring Superbomberman." },
  { name: "Mario Paint", url: "https://olivia-games.github.io/seraph/games/mariopaint/index.html", category: "platformer", description: "Mariopaint challenges your timing and movement skills." },
  { name: "Mega Man X", url: "https://olivia-games.github.io/seraph/games/megamanx/index.html", category: "action", description: "Megamanx delivers nonstop arcade-style action." },
  { name: "Super Mario RPG", url: "https://olivia-games.github.io/seraph/games/supermariorpg/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Supermariorpg." },
  { name: "Super Tennis", url: "https://olivia-games.github.io/seraph/games/supertennis/index.html", category: "action", description: "React quickly and survive intense action in Supertennis." },
  { name: "Wario's Woods", url: "https://olivia-games.github.io/seraph/games/warioswoods/index.html", category: "action", description: "Warioswoods delivers nonstop arcade-style action." },
  { name: "World's Hardest Game 2", url: "https://olivia-games.github.io/seraph/games/worldshardestgame2/index.html", category: "action", description: "Fast-paced action challenge featuring Worldshardestgame2." },
  { name: "Bubble Tanks 2", url: "https://olivia-games.github.io/seraph/games/bubbletanks2/index.html", category: "action", description: "React quickly and survive intense action in Bubbletanks2." },
  { name: "Choose Your Weapon", url: "https://olivia-games.github.io/seraph/games/chooseyourweapon/index.html", category: "action", description: "Chooseyourweapon delivers nonstop arcade-style action." },
  { name: "Choose Your Weapon 2", url: "https://olivia-games.github.io/seraph/games/chooseyourweapon2/index.html", category: "action", description: "Fast-paced action challenge featuring Chooseyourweapon2." },
  { name: "Choose Your Weapon 3", url: "https://olivia-games.github.io/seraph/games/chooseyourweapon3/index.html", category: "action", description: "React quickly and survive intense action in Chooseyourweapon3." },
  { name: "Connect 4", url: "https://olivia-games.github.io/seraph/games/connect4/index.html", category: "action", description: "Connect4 delivers nonstop arcade-style action." },
  { name: "Electric Box", url: "https://olivia-games.github.io/seraph/games/electricbox/index.html", category: "action", description: "Fast-paced action challenge featuring Electricbox." },
  { name: "MC Tower Defence 2", url: "https://olivia-games.github.io/seraph/games/mctowerdefence2/index.html", category: "action", description: "React quickly and survive intense action in Mctowerdefence2." },
  { name: "Cars 2", url: "https://olivia-games.github.io/seraph/games/cars2/index.html", category: "action", description: "Cars2 delivers nonstop arcade-style action." },
  { name: "Cooking Mama", url: "https://olivia-games.github.io/seraph/games/cookingmama/index.html", category: "restaurant", description: "Cook, serve, and manage customers in Cookingmama." },
  { name: "Adventure Time", url: "https://olivia-games.github.io/seraph/games/adventuretime/index.html", category: "action", description: "React quickly and survive intense action in Adventuretime." },
  { name: "Garfield Gets Real", url: "https://olivia-games.github.io/seraph/games/garfieldgetsreal/index.html", category: "action", description: "Garfieldgetsreal delivers nonstop arcade-style action." },
  { name: "WarioWare Touched!", url: "https://olivia-games.github.io/seraph/games/wariowaretouched/index.html", category: "action", description: "Fast-paced action challenge featuring Wariowaretouched." },
  { name: "Kirby: Power Paintbrush", url: "https://olivia-games.github.io/seraph/games/kirbypowerpaintbrush/index.html", category: "platformer", description: "Kirbypowerpaintbrush challenges your timing and movement skills." },
  { name: "Sonic & Knuckles", url: "https://olivia-games.github.io/seraph/games/sonicandknuckles/index.html", category: "platformer", description: "A skill-based platforming adventure called Sonicandknuckles." },
  { name: "Altered Beast", url: "https://olivia-games.github.io/seraph/games/alteredbeast/index.html", category: "action", description: "Fast-paced action challenge featuring Alteredbeast." },
  { name: "Sonic Spinball", url: "https://olivia-games.github.io/seraph/games/sonicspinball/index.html", category: "platformer", description: "Sonicspinball challenges your timing and movement skills." },
  { name: "Sonic the Hedgehog 3", url: "https://olivia-games.github.io/seraph/games/sonicthehedgehog3/index.html", category: "platformer", description: "A skill-based platforming adventure called Sonicthehedgehog3." },
  { name: "Streets of Rage", url: "https://olivia-games.github.io/seraph/games/streetsofrage/index.html", category: "action", description: "Fast-paced action challenge featuring Streetsofrage." },
  { name: "Golden Axe", url: "https://olivia-games.github.io/seraph/games/goldenaxe/index.html", category: "action", description: "React quickly and survive intense action in Goldenaxe." },
  { name: "Kirby & the Amazing Mirror", url: "https://olivia-games.github.io/seraph/games/kirbyamazingmirror/index.html", category: "platformer", description: "A skill-based platforming adventure called Kirbyamazingmirror." },
  { name: "Champion Island", url: "https://olivia-games.github.io/seraph/games/championisland/index.html", category: "action", description: "Fast-paced action challenge featuring Championisland." },
  { name: "Super Mario Construct", url: "https://olivia-games.github.io/seraph/games/supermarioconstruct/index.html", category: "platformer", description: "Supermarioconstruct challenges your timing and movement skills." },
  { name: "Clicker Heroes", url: "https://olivia-games.github.io/seraph/games/clickerheroes/index.html", category: "strategy", description: "A strategic gameplay experience built around Clickerheroes." },
  { name: "Stair Race 3D", url: "https://olivia-games.github.io/seraph/games/stairrace3d/index.html", category: "action", description: "Fast-paced action challenge featuring Stairrace3d." },
  { name: "Slope 2", url: "https://olivia-games.github.io/seraph/games/slope2/index.html", category: "action", description: "React quickly and survive intense action in Slope2." },
  { name: "Paper.io 3D", url: "https://olivia-games.github.io/seraph/games/paperio3d/index.html", category: "action", description: "Paperio3d delivers nonstop arcade-style action." },
  { name: "Moto X3M Spooky", url: "https://olivia-games.github.io/seraph/games/motox3mspooky/index.html", category: "racing", description: "Race at high speed and master the tracks in Motox3mspooky." },
  { name: "Moto X3M Winter", url: "https://olivia-games.github.io/seraph/games/motox3mwinter/index.html", category: "racing", description: "Motox3mwinter puts your driving skills to the test." },
  { name: "Snake", url: "https://olivia-games.github.io/seraph/games/snake/index.html", category: "action", description: "Snake delivers nonstop arcade-style action." },
  { name: "Papa's Taco Mia", url: "https://olivia-games.github.io/seraph/games/papastacomia/index.html", category: "restaurant", description: "Cook, serve, and manage customers in Papastacomia." },
  { name: "Ovo", url: "https://olivia-games.github.io/seraph/games/ovo/index.html", category: "action", description: "React quickly and survive intense action in Ovo." },
  { name: "Knife Hit", url: "https://olivia-games.github.io/seraph/games/knifehit/index.html", category: "action", description: "Knifehit delivers nonstop arcade-style action." },
  { name: "Cube Field", url: "https://olivia-games.github.io/seraph/games/cubefield/index.html", category: "action", description: "Fast-paced action challenge featuring Cubefield." },
  { name: "Burger and Frights", url: "https://olivia-games.github.io/seraph/games/burgerandfrights/index.html", category: "action", description: "React quickly and survive intense action in Burgerandfrights." },
  { name: "Chess", url: "https://olivia-games.github.io/seraph/games/chess/index.html", category: "puzzle", description: "A thoughtful puzzle experience named Chess." },
  { name: "FNF Mid-Fight", url: "https://olivia-games.github.io/seraph/games/fnfmidfight/index.html", category: "music", description: "Follow the rhythm and hit the beats in Fnfmidfight." },
  { name: "Thumb Fighter", url: "https://olivia-games.github.io/seraph/games/thumbfighter/index.html", category: "fighting", description: "Thumbfighter focuses on fast and competitive fighting." },
  { name: "Snow Battle IO", url: "https://olivia-games.github.io/seraph/games/snowbattleio/index.html", category: "action", description: "Snowbattleio delivers nonstop arcade-style action." },
  { name: "Lazy Jump 3D", url: "https://olivia-games.github.io/seraph/games/lazyjump3d/index.html", category: "action", description: "Fast-paced action challenge featuring Lazyjump3d." },
  { name: "Go Ball", url: "https://olivia-games.github.io/seraph/games/goball/index.html", category: "action", description: "React quickly and survive intense action in Goball." },
  { name: "Flippy Fish", url: "https://olivia-games.github.io/seraph/games/flippyfish/index.html", category: "action", description: "Flippyfish delivers nonstop arcade-style action." },
  { name: "Shop Empire", url: "https://olivia-games.github.io/seraph/games/shopempire/index.html", category: "action", description: "Fast-paced action challenge featuring Shopempire." },
  { name: "Monster Brawl", url: "https://olivia-games.github.io/seraph/games/monsterbrawl/index.html", category: "action", description: "React quickly and survive intense action in Monsterbrawl." },
  { name: "Multitask", url: "https://olivia-games.github.io/seraph/games/multitask/index.html", category: "action", description: "Multitask delivers nonstop arcade-style action." },
  { name: "Shift", url: "https://olivia-games.github.io/seraph/games/shift/index.html", category: "action", description: "Fast-paced action challenge featuring Shift." },
  { name: "Shift 2", url: "https://olivia-games.github.io/seraph/games/shift2/index.html", category: "action", description: "React quickly and survive intense action in Shift2." },
  { name: "Shift 3", url: "https://olivia-games.github.io/seraph/games/shift3/index.html", category: "action", description: "Shift3 delivers nonstop arcade-style action." },
  { name: "Shift 4", url: "https://olivia-games.github.io/seraph/games/shift4/index.html", category: "action", description: "Fast-paced action challenge featuring Shift4." },
  { name: "Monopoly", url: "https://olivia-games.github.io/seraph/games/monopoly/index.html", category: "action", description: "React quickly and survive intense action in Monopoly." },
  { name: "Picross DS", url: "https://olivia-games.github.io/seraph/games/picrossds/index.html", category: "action", description: "Picrossds delivers nonstop arcade-style action." },
  { name: "WarioWare D.I.Y.", url: "https://olivia-games.github.io/seraph/games/wariowarediy/index.html", category: "action", description: "Fast-paced action challenge featuring Wariowarediy." },
  { name: "Pizza Tower", url: "https://olivia-games.github.io/seraph/games/pizzatower/index.html", category: "action", description: "React quickly and survive intense action in Pizzatower." },
  { name: "Territorial IO", url: "https://olivia-games.github.io/seraph/games/territorialio/index.html", category: "action", description: "Territorialio delivers nonstop arcade-style action." },
  { name: "1v1 LOL", url: "https://olivia-games.github.io/seraph/games/1v1lol/index.html", category: "action", description: "Fast-paced action challenge featuring 1v1lol." },
  { name: "Ballistic Chickens", url: "https://olivia-games.github.io/seraph/games/ballisticchickens/index.html", category: "action", description: "React quickly and survive intense action in Ballisticchickens." },
  { name: "Basket Bros IO", url: "https://olivia-games.github.io/seraph/games/basketbrosio/index.html", category: "action", description: "Basketbrosio delivers nonstop arcade-style action." },
  { name: "MC Classic", url: "https://olivia-games.github.io/seraph/games/mcclassic/index.html", category: "action", description: "Fast-paced action challenge featuring Mcclassic." },
  { name: "Death Run 3D", url: "https://olivia-games.github.io/seraph/games/deathrun3d/index.html", category: "action", description: "React quickly and survive intense action in Deathrun3d." },
  { name: "Soccer Random", url: "https://olivia-games.github.io/seraph/games/soccerrandom/index.html", category: "action", description: "Soccerrandom delivers nonstop arcade-style action." },
  { name: "Sprinter", url: "https://olivia-games.github.io/seraph/games/sprinter/index.html", category: "action", description: "Fast-paced action challenge featuring Sprinter." },
  { name: "Tron", url: "https://olivia-games.github.io/seraph/games/tron/index.html", category: "action", description: "React quickly and survive intense action in Tron." },
  { name: "1 on 1 Soccer", url: "https://olivia-games.github.io/seraph/games/1on1soccer/index.html", category: "action", description: "1on1soccer delivers nonstop arcade-style action." },
  { name: "Bad Time Simulator", url: "https://olivia-games.github.io/seraph/games/badtimesimulator/index.html", category: "action", description: "Fast-paced action challenge featuring Badtimesimulator." },
  { name: "Amazing Rope Police", url: "https://olivia-games.github.io/seraph/games/amazingropepolice/index.html", category: "action", description: "React quickly and survive intense action in Amazingropepolice." },
  { name: "Celeste", url: "https://olivia-games.github.io/seraph/games/celeste/index.html", category: "action", description: "Celeste delivers nonstop arcade-style action." },
  { name: "Just Fall LOL", url: "https://olivia-games.github.io/seraph/games/justfalllol/index.html", category: "action", description: "Fast-paced action challenge featuring Justfalllol." },
  { name: "N-Gon", url: "https://olivia-games.github.io/seraph/games/ngon/index.html", category: "action", description: "React quickly and survive intense action in Ngon." },
  { name: "Rocket Soccer", url: "https://olivia-games.github.io/seraph/games/rocketsoccer/index.html", category: "action", description: "Rocketsoccer delivers nonstop arcade-style action." },
  { name: "Stickman Climb", url: "https://olivia-games.github.io/seraph/games/stickmanclimb/index.html", category: "action", description: "Fast-paced action challenge featuring Stickmanclimb." },
  { name: "Osu! Mania", url: "https://olivia-games.github.io/seraph/games/osumania/index.html", category: "action", description: "React quickly and survive intense action in Osumania." },
  { name: "Helix Jump", url: "https://olivia-games.github.io/seraph/games/helixjump/index.html", category: "action", description: "Helixjump delivers nonstop arcade-style action." },
  { name: "Dadish", url: "https://olivia-games.github.io/seraph/games/dadish/index.html", category: "action", description: "Fast-paced action challenge featuring Dadish." },
  { name: "Dadish 2", url: "https://olivia-games.github.io/seraph/games/dadish2/index.html", category: "action", description: "React quickly and survive intense action in Dadish2." },
  { name: "Dadish 3", url: "https://olivia-games.github.io/seraph/games/dadish3/index.html", category: "action", description: "Dadish3 delivers nonstop arcade-style action." },
  { name: "Snow Rider 3D", url: "https://olivia-games.github.io/seraph/games/snowrider3d/index.html", category: "action", description: "Fast-paced action challenge featuring Snowrider3d." },
  { name: "Tube Jumpers", url: "https://olivia-games.github.io/seraph/games/tubejumpers/index.html", category: "action", description: "React quickly and survive intense action in Tubejumpers." },
  { name: "Yohoho", url: "https://olivia-games.github.io/seraph/games/yohoho/index.html", category: "action", description: "Yohoho delivers nonstop arcade-style action." },
  { name: "10 Minutes Till Dawn", url: "https://olivia-games.github.io/seraph/games/10minutestilldawn/index.html", category: "action", description: "Fast-paced action challenge featuring 10minutestilldawn." },
  { name: "Volley Random", url: "https://olivia-games.github.io/seraph/games/volleyrandom/index.html", category: "action", description: "React quickly and survive intense action in Volleyrandom." },
  { name: "Waterworks", url: "https://olivia-games.github.io/seraph/games/waterworks/index.html", category: "action", description: "Waterworks delivers nonstop arcade-style action." },
  { name: "Geometry Rash", url: "https://olivia-games.github.io/seraph/games/geometryrash/index.html", category: "action", description: "Fast-paced action challenge featuring Geometryrash." },
  { name: "Hole IO", url: "https://olivia-games.github.io/seraph/games/holeio/index.html", category: "action", description: "React quickly and survive intense action in Holeio." },
  { name: "Sandtrix", url: "https://olivia-games.github.io/seraph/games/sandtrix/index.html", category: "action", description: "Sandtrix delivers nonstop arcade-style action." },
  { name: "Shape Shipper", url: "https://olivia-games.github.io/seraph/games/shapeshipper/index.html", category: "action", description: "Fast-paced action challenge featuring Shapeshipper." },
  { name: "Slope Ball", url: "https://olivia-games.github.io/seraph/games/slopeball/index.html", category: "action", description: "React quickly and survive intense action in Slopeball." },
  { name: "Stickman Golf", url: "https://olivia-games.github.io/seraph/games/stickmangolf/index.html", category: "action", description: "Stickmangolf delivers nonstop arcade-style action." },
  { name: "TABS", url: "https://olivia-games.github.io/seraph/games/tabs/index.html", category: "action", description: "Fast-paced action challenge featuring Tabs." },
  { name: "Watermelon Game", url: "https://olivia-games.github.io/seraph/games/watermelongame/index.html", category: "action", description: "React quickly and survive intense action in Watermelongame." },
  { name: "Wall Smash", url: "https://olivia-games.github.io/seraph/games/wallsmash/index.html", category: "fighting", description: "Test your reflexes and combos in Wallsmash." },
  { name: "Crimson Fantasia", url: "https://olivia-games.github.io/seraph/games/crimsonfantasia/index.html", category: "action", description: "Fast-paced action challenge featuring Crimsonfantasia." },
  { name: "Cut the Rope", url: "https://olivia-games.github.io/seraph/games/cuttherope/index.html", category: "action", description: "React quickly and survive intense action in Cuttherope." },
  { name: "Funny Mad Racing", url: "https://olivia-games.github.io/seraph/games/funnymadracing/index.html", category: "racing", description: "Fast and competitive racing action in Funnymadracing." },
  { name: "GD Lite", url: "https://olivia-games.github.io/seraph/games/gdlite/index.html", category: "action", description: "Fast-paced action challenge featuring Gdlite." },
  { name: "Grand Theft Grotto", url: "https://olivia-games.github.io/seraph/games/grandtheftgrotto/index.html", category: "action", description: "React quickly and survive intense action in Grandtheftgrotto." },
  { name: "Drift Mania", url: "https://olivia-games.github.io/seraph/games/driftmania/index.html", category: "racing", description: "Fast and competitive racing action in Driftmania." },
  { name: "Rise Higher", url: "https://olivia-games.github.io/seraph/games/risehigher/index.html", category: "action", description: "Fast-paced action challenge featuring Risehigher." },
  { name: "Burrito Bison", url: "https://olivia-games.github.io/seraph/games/burritobison/index.html", category: "action", description: "React quickly and survive intense action in Burritobison." },
  { name: "Pool", url: "https://olivia-games.github.io/seraph/games/pool/index.html", category: "action", description: "Pool delivers nonstop arcade-style action." },
  { name: "Red Ball 1", url: "https://olivia-games.github.io/seraph/games/redball1/index.html", category: "action", description: "Fast-paced action challenge featuring Redball1." },
  { name: "Red Ball 3", url: "https://olivia-games.github.io/seraph/games/redball3/index.html", category: "action", description: "React quickly and survive intense action in Redball3." },
  { name: "Red Ball 4", url: "https://olivia-games.github.io/seraph/games/redball4/index.html", category: "action", description: "Redball4 delivers nonstop arcade-style action." },
  { name: "Red Ball V2", url: "https://olivia-games.github.io/seraph/games/redballv2/index.html", category: "action", description: "Fast-paced action challenge featuring Redballv2." },
  { name: "Red Ball V3", url: "https://olivia-games.github.io/seraph/games/redballv3/index.html", category: "action", description: "React quickly and survive intense action in Redballv3." },
  { name: "Rough Dino", url: "https://olivia-games.github.io/seraph/games/roughdino/index.html", category: "action", description: "Roughdino delivers nonstop arcade-style action." },
  { name: "Time Shooter 1", url: "https://olivia-games.github.io/seraph/games/timeshooter1/index.html", category: "action", description: "Fast-paced action challenge featuring Timeshooter1." },
  { name: "Time Shooter 2", url: "https://olivia-games.github.io/seraph/games/timeshooter2/index.html", category: "action", description: "React quickly and survive intense action in Timeshooter2." },
  { name: "Time Shooter 3", url: "https://olivia-games.github.io/seraph/games/timeshooter3/index.html", category: "action", description: "Timeshooter3 delivers nonstop arcade-style action." },
  { name: "Battletoads", url: "https://olivia-games.github.io/seraph/games/battletoads/index.html", category: "action", description: "Fast-paced action challenge featuring Battletoads." },
  { name: "Castlevania III", url: "https://olivia-games.github.io/seraph/games/castlevaniaiii/index.html", category: "action", description: "React quickly and survive intense action in Castlevaniaiii." },
  { name: "Contra", url: "https://olivia-games.github.io/seraph/games/contra/index.html", category: "action", description: "Contra delivers nonstop arcade-style action." },
  { name: "DuckTales", url: "https://olivia-games.github.io/seraph/games/ducktales/index.html", category: "action", description: "Fast-paced action challenge featuring Ducktales." },
  { name: "Kid Icarus", url: "https://olivia-games.github.io/seraph/games/kidicarus/index.html", category: "action", description: "React quickly and survive intense action in Kidicarus." },
  { name: "Mega Man 2", url: "https://olivia-games.github.io/seraph/games/megaman2/index.html", category: "action", description: "Megaman2 delivers nonstop arcade-style action." },
  { name: "Ninja Gaiden", url: "https://olivia-games.github.io/seraph/games/ninjagaiden/index.html", category: "action", description: "Fast-paced action challenge featuring Ninjagaiden." },
  { name: "Punch-Out!!", url: "https://olivia-games.github.io/seraph/games/punchout/index.html", category: "action", description: "React quickly and survive intense action in Punchout." },
  { name: "Chrono Trigger", url: "https://olivia-games.github.io/seraph/games/chronotrigger/index.html", category: "action", description: "Chronotrigger delivers nonstop arcade-style action." },
  { name: "Contra III", url: "https://olivia-games.github.io/seraph/games/contraiii/index.html", category: "action", description: "Fast-paced action challenge featuring Contraiii." },
  { name: "Donkey Kong Country 3", url: "https://olivia-games.github.io/seraph/games/donkeykongcountry3/index.html", category: "action", description: "React quickly and survive intense action in Donkeykongcountry3." },
  { name: "EarthBound", url: "https://olivia-games.github.io/seraph/games/earthbound/index.html", category: "rpg", description: "An RPG adventure filled with depth: Earthbound." },
  { name: "Final Fantasy VI", url: "https://olivia-games.github.io/seraph/games/finalfantasyvi/index.html", category: "rpg", description: "Embark on an epic role-playing journey in Finalfantasyvi." },
  { name: "F-Zero", url: "https://olivia-games.github.io/seraph/games/fzero/index.html", category: "action", description: "React quickly and survive intense action in Fzero." },
  { name: "Super Metroid", url: "https://olivia-games.github.io/seraph/games/supermetroid/index.html", category: "platformer", description: "A skill-based platforming adventure called Supermetroid." },
  { name: "Banjo-Tooie", url: "https://olivia-games.github.io/seraph/games/banjotooie/index.html", category: "action", description: "Fast-paced action challenge featuring Banjotooie." },
  { name: "Harvest Moon 64", url: "https://olivia-games.github.io/seraph/games/harvestmoon64/index.html", category: "action", description: "React quickly and survive intense action in Harvestmoon64." },
  { name: "Jet Force Gemini", url: "https://olivia-games.github.io/seraph/games/jetforcegemini/index.html", category: "action", description: "Jetforcegemini delivers nonstop arcade-style action." },
  { name: "Mystical Ninja", url: "https://olivia-games.github.io/seraph/games/mysticalninja/index.html", category: "action", description: "Fast-paced action challenge featuring Mysticalninja." },
  { name: "Turok: Dinosaur Hunter", url: "https://olivia-games.github.io/seraph/games/turokdinosaurhunter/index.html", category: "action", description: "React quickly and survive intense action in Turokdinosaurhunter." },
  { name: "Yoshi's Story", url: "https://olivia-games.github.io/seraph/games/yoshisstory/index.html", category: "action", description: "Yoshisstory delivers nonstop arcade-style action." },
  { name: "Kirby's Dream Land 2", url: "https://olivia-games.github.io/seraph/games/kirbysdreamland2/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Kirbysdreamland2." },
  { name: "Link's Awakening DX", url: "https://olivia-games.github.io/seraph/games/linksawakeningdx/index.html", category: "action", description: "React quickly and survive intense action in Linksawakeningdx." },
  { name: "Metroid II", url: "https://olivia-games.github.io/seraph/games/metroidii/index.html", category: "platformer", description: "A skill-based platforming adventure called Metroidii." },
  { name: "Super Mario Land 2", url: "https://olivia-games.github.io/seraph/games/supermarioland2/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Supermarioland2." },
  { name: "Wario Land II", url: "https://olivia-games.github.io/seraph/games/wariolandii/index.html", category: "action", description: "React quickly and survive intense action in Wariolandii." },
  { name: "Castlevania: Aria of Sorrow", url: "https://olivia-games.github.io/seraph/games/castlevaniaariaofsorrow/index.html", category: "action", description: "Castlevaniaariaofsorrow delivers nonstop arcade-style action." },
  { name: "Final Fantasy Tactics Advance", url: "https://olivia-games.github.io/seraph/games/finalfantasytacticsadvance/index.html", category: "rpg", description: "Embark on an epic role-playing journey in Finalfantasytacticsadvance." },
  { name: "Drill Dozer", url: "https://olivia-games.github.io/seraph/games/drilldozer/index.html", category: "action", description: "React quickly and survive intense action in Drilldozer." },
  { name: "Advance Wars: Days of Ruin", url: "https://olivia-games.github.io/seraph/games/advancewarsdayofruin/index.html", category: "action", description: "Advancewarsdayofruin delivers nonstop arcade-style action." },
  { name: "Castlevania: Dawn of Sorrow", url: "https://olivia-games.github.io/seraph/games/castlevaniadawnofsorrow/index.html", category: "action", description: "Fast-paced action challenge featuring Castlevaniadawnofsorrow." },
  { name: "Castlevania: Order of Ecclesia", url: "https://olivia-games.github.io/seraph/games/castlevaniaorderofecclesia/index.html", category: "action", description: "React quickly and survive intense action in Castlevaniaorderofecclesia." },
  { name: "Mario & Luigi: Partners in Time", url: "https://olivia-games.github.io/seraph/games/marioandluigipartnersintime/index.html", category: "platformer", description: "A skill-based platforming adventure called Marioandluigipartnersintime." },
  { name: "Comix Zone", url: "https://olivia-games.github.io/seraph/games/comixzone/index.html", category: "action", description: "Fast-paced action challenge featuring Comixzone." },
  { name: "Ecco the Dolphin", url: "https://olivia-games.github.io/seraph/games/eccothedolphin/index.html", category: "action", description: "React quickly and survive intense action in Eccothedolphin." },
  { name: "Gunstar Heroes", url: "https://olivia-games.github.io/seraph/games/gunstarheroes/index.html", category: "action", description: "Gunstarheroes delivers nonstop arcade-style action." },
  { name: "Phantasy Star IV", url: "https://olivia-games.github.io/seraph/games/phantasystariv/index.html", category: "action", description: "Fast-paced action challenge featuring Phantasystariv." },
  { name: "Ranger X", url: "https://olivia-games.github.io/seraph/games/rangerx/index.html", category: "action", description: "React quickly and survive intense action in Rangerx." },
  { name: "Ristar", url: "https://olivia-games.github.io/seraph/games/ristar/index.html", category: "action", description: "Ristar delivers nonstop arcade-style action." },
  { name: "Shining Force", url: "https://olivia-games.github.io/seraph/games/shiningforce/index.html", category: "action", description: "Fast-paced action challenge featuring Shiningforce." },
  { name: "Shinobi III", url: "https://olivia-games.github.io/seraph/games/shinobiiii/index.html", category: "action", description: "React quickly and survive intense action in Shinobiiii." },
  { name: "Sonic the Hedgehog", url: "https://olivia-games.github.io/seraph/games/sonicthehedgehog/index.html", category: "platformer", description: "A skill-based platforming adventure called Sonicthehedgehog." },
  { name: "Sonic the Hedgehog 2", url: "https://olivia-games.github.io/seraph/games/sonicthehedgehog2/index.html", category: "platformer", description: "Jump, run, and explore classic platforming in Sonicthehedgehog2." },
  { name: "Streets of Rage 2", url: "https://olivia-games.github.io/seraph/games/streetsofrage2/index.html", category: "action", description: "React quickly and survive intense action in Streetsofrage2." },
  { name: "Vectorman", url: "https://olivia-games.github.io/seraph/games/vectorman/index.html", category: "action", description: "Vectorman delivers nonstop arcade-style action." },
  { name: "Vectorman 2", url: "https://olivia-games.github.io/seraph/games/vectorman2/index.html", category: "action", description: "Fast-paced action challenge featuring Vectorman2." },
  { name: "Illusion of Gaia", url: "https://olivia-games.github.io/seraph/games/illusionofgaia/index.html", category: "action", description: "React quickly and survive intense action in Illusionofgaia." },
  { name: "Pokemon Yellow", url: "https://olivia-games.github.io/seraph/games/pokemonyellow/index.html", category: "rpg", description: "An RPG adventure filled with depth: Pokemonyellow." },
  { name: "Abuda the Alien", url: "https://olivia-games.github.io/seraph/games/abudathealien/index.html", category: "action", description: "Fast-paced action challenge featuring Abudathealien." },
  { name: "Battle Beavers", url: "https://olivia-games.github.io/seraph/games/battlebeavers/index.html", category: "action", description: "React quickly and survive intense action in Battlebeavers." },
  { name: "Control Craft 2", url: "https://olivia-games.github.io/seraph/games/controlcraft2/index.html", category: "action", description: "Controlcraft2 delivers nonstop arcade-style action." },
  { name: "Age of War", url: "https://olivia-games.github.io/seraph/games/ageofwar/index.html", category: "action", description: "Fast-paced action challenge featuring Ageofwar." },
  { name: "Age of War 2", url: "https://olivia-games.github.io/seraph/games/ageofwar2/index.html", category: "action", description: "React quickly and survive intense action in Ageofwar2." },
  { name: "Amorphous", url: "https://olivia-games.github.io/seraph/games/amorphous/index.html", category: "action", description: "Amorphous delivers nonstop arcade-style action." },
  { name: "Bubble Spinner", url: "https://olivia-games.github.io/seraph/games/bubblespinner/index.html", category: "action", description: "Fast-paced action challenge featuring Bubblespinner." },
  { name: "Crush the Castle", url: "https://olivia-games.github.io/seraph/games/crushthecastle/index.html", category: "action", description: "React quickly and survive intense action in Crushthecastle." },
  { name: "Crush the Castle 2", url: "https://olivia-games.github.io/seraph/games/crushthecastle2/index.html", category: "action", description: "Crushthecastle2 delivers nonstop arcade-style action." },
  { name: "Epic Battle Fantasy", url: "https://olivia-games.github.io/seraph/games/epicbattlefantasy/index.html", category: "action", description: "Fast-paced action challenge featuring Epicbattlefantasy." },
  { name: "Epic Battle Fantasy 2", url: "https://olivia-games.github.io/seraph/games/epicbattlefantasy2/index.html", category: "action", description: "React quickly and survive intense action in Epicbattlefantasy2." },
  { name: "Epic Battle Fantasy 3", url: "https://olivia-games.github.io/seraph/games/epicbattlefantasy3/index.html", category: "action", description: "Epicbattlefantasy3 delivers nonstop arcade-style action." },
  { name: "Fancy Pants Adventure 3", url: "https://olivia-games.github.io/seraph/games/fancypantsadventure3/index.html", category: "action", description: "Fast-paced action challenge featuring Fancypantsadventure3." },
  { name: "Flood Runner 2", url: "https://olivia-games.github.io/seraph/games/floodrunner2/index.html", category: "action", description: "React quickly and survive intense action in Floodrunner2." },
  { name: "Flood Runner 3", url: "https://olivia-games.github.io/seraph/games/floodrunner3/index.html", category: "action", description: "Floodrunner3 delivers nonstop arcade-style action." },
  { name: "Dragon Boy 2", url: "https://olivia-games.github.io/seraph/games/dragonboy2/index.html", category: "action", description: "Fast-paced action challenge featuring Dragonboy2." },
  { name: "Neon Rider", url: "https://olivia-games.github.io/seraph/games/neonrider/index.html", category: "action", description: "React quickly and survive intense action in Neonrider." },
  { name: "Pandemic 2", url: "https://olivia-games.github.io/seraph/games/pandemic2/index.html", category: "action", description: "Pandemic2 delivers nonstop arcade-style action." },
  { name: "Stick War", url: "https://olivia-games.github.io/seraph/games/stickwar/index.html", category: "action", description: "Fast-paced action challenge featuring Stickwar." },
  { name: "Stick War 2", url: "https://olivia-games.github.io/seraph/games/stickwar2/index.html", category: "action", description: "React quickly and survive intense action in Stickwar2." },
  { name: "Ultimate Flash Sonic", url: "https://olivia-games.github.io/seraph/games/ultimateflashsonic/index.html", category: "platformer", description: "A skill-based platforming adventure called Ultimateflashsonic." },
  { name: "Zombocalypse", url: "https://olivia-games.github.io/seraph/games/zombocalypse/index.html", category: "action", description: "Fast-paced action challenge featuring Zombocalypse." },
  { name: "Zombotron", url: "https://olivia-games.github.io/seraph/games/zombotron/index.html", category: "action", description: "React quickly and survive intense action in Zombotron." },
  { name: "Zombotron 2", url: "https://olivia-games.github.io/seraph/games/zombotron2/index.html", category: "action", description: "Zombotron2 delivers nonstop arcade-style action." },
  { name: "Backrooms 2D", url: "https://olivia-games.github.io/seraph/games/backrooms2d/index.html", category: "horror", description: "A tense and scary experience awaits in Backrooms2d." },
  { name: "Basket Random", url: "https://olivia-games.github.io/seraph/games/basketrandom/index.html", category: "action", description: "React quickly and survive intense action in Basketrandom." },
  { name: "CSGO Clicker", url: "https://olivia-games.github.io/seraph/games/csgoclicker/index.html", category: "strategy", description: "A strategic gameplay experience built around Csgoclicker." },
  { name: "Doom", url: "https://olivia-games.github.io/seraph/games/doom/index.html", category: "action", description: "Fast-paced action challenge featuring Doom." },
  { name: "Funny Shooter 2", url: "https://olivia-games.github.io/seraph/games/funnyshooter2/index.html", category: "action", description: "React quickly and survive intense action in Funnyshooter2." },
  { name: "Gunfest", url: "https://olivia-games.github.io/seraph/games/gunfest/index.html", category: "action", description: "Gunfest delivers nonstop arcade-style action." },
  { name: "Infinite Craft", url: "https://olivia-games.github.io/seraph/games/infinitecraft/index.html", category: "action", description: "Fast-paced action challenge featuring Infinitecraft." },
  { name: "Lows Adventures 2", url: "https://olivia-games.github.io/seraph/games/lowsadventures2/index.html", category: "action", description: "React quickly and survive intense action in Lowsadventures2." },
  { name: "Pako Highway", url: "https://olivia-games.github.io/seraph/games/pakohighway/index.html", category: "action", description: "Pakohighway delivers nonstop arcade-style action." },
  { name: "Recoil", url: "https://olivia-games.github.io/seraph/games/recoil/index.html", category: "action", description: "Fast-paced action challenge featuring Recoil." },
  { name: "Run 3 Plus", url: "https://olivia-games.github.io/seraph/games/run3plus/index.html", category: "action", description: "React quickly and survive intense action in Run3plus." },
  { name: "Slope City", url: "https://olivia-games.github.io/seraph/games/slopecity/index.html", category: "action", description: "Slopecity delivers nonstop arcade-style action." },
  { name: "State IO", url: "https://olivia-games.github.io/seraph/games/stateio/index.html", category: "action", description: "Fast-paced action challenge featuring Stateio." },
  { name: "Sudoku", url: "https://olivia-games.github.io/seraph/games/sudoku/index.html", category: "puzzle", description: "Sudoku challenges logic and problem-solving skills." },
  { name: "Superhero Drop", url: "https://olivia-games.github.io/seraph/games/superherodrop/index.html", category: "action", description: "Superherodrop delivers nonstop arcade-style action." },
  { name: "Balloon Run", url: "https://olivia-games.github.io/seraph/games/balloonrun/index.html", category: "action", description: "Fast-paced action challenge featuring Balloonrun." },
  { name: "Crazy Tunnel 3D", url: "https://olivia-games.github.io/seraph/games/crazytunnel3d/index.html", category: "action", description: "React quickly and survive intense action in Crazytunnel3d." },
  { name: "Eagler 1.8", url: "https://olivia-games.github.io/seraph/games/eagler1.8/index.html", category: "action", description: "Eagler1.8 delivers nonstop arcade-style action." },
  { name: "Geometry Dash Sky", url: "https://olivia-games.github.io/seraph/games/geometrydashsky/index.html", category: "action", description: "Fast-paced action challenge featuring Geometrydashsky." },
  { name: "Wubzzy's Amazing Adventure", url: "https://olivia-games.github.io/seraph/games/wubzzysamazingadventure/index.html", category: "action", description: "React quickly and survive intense action in Wubzzysamazingadventure." },
  { name: "Gold Digger FRVR", url: "https://olivia-games.github.io/seraph/games/golddiggerfrvr/index.html", category: "action", description: "Golddiggerfrvr delivers nonstop arcade-style action." },
  { name: "HexGL", url: "https://olivia-games.github.io/seraph/games/hexgl/index.html", category: "action", description: "Fast-paced action challenge featuring Hexgl." },
  { name: "House of Hazards", url: "https://olivia-games.github.io/seraph/games/houseofhazards/index.html", category: "action", description: "React quickly and survive intense action in Houseofhazards." },
  { name: "Pickcrafter", url: "https://olivia-games.github.io/seraph/games/pickcrafter/index.html", category: "action", description: "Pickcrafter delivers nonstop arcade-style action." },
  { name: "Precision Client", url: "https://olivia-games.github.io/seraph/games/precisionclient/index.html", category: "action", description: "Fast-paced action challenge featuring Precisionclient." },
  { name: "Subway Runner", url: "https://olivia-games.github.io/seraph/games/subwayrunner/index.html", category: "action", description: "React quickly and survive intense action in Subwayrunner." },
  { name: "XX142 B2.EXE", url: "https://olivia-games.github.io/seraph/games/xx142-b2.exe/index.html", category: "action", description: "Xx142 B2.Exe delivers nonstop arcade-style action." },
  { name: "Canopy", url: "https://olivia-games.github.io/seraph/games/canopy/index.html", category: "action", description: "Fast-paced action challenge featuring Canopy." },
  { name: "Cave Chaos", url: "https://olivia-games.github.io/seraph/games/cavechaos/index.html", category: "action", description: "React quickly and survive intense action in Cavechaos." },
  { name: "Change Type", url: "https://olivia-games.github.io/seraph/games/changetype/index.html", category: "action", description: "Changetype delivers nonstop arcade-style action." },
  { name: "Cheese Dreams", url: "https://olivia-games.github.io/seraph/games/cheesedreams/index.html", category: "action", description: "Fast-paced action challenge featuring Cheesedreams." },
  { name: "Chisel", url: "https://olivia-games.github.io/seraph/games/chisel/index.html", category: "action", description: "React quickly and survive intense action in Chisel." },
  { name: "Chisel 2", url: "https://olivia-games.github.io/seraph/games/chisel2/index.html", category: "action", description: "Chisel2 delivers nonstop arcade-style action." },
  { name: "Ditto", url: "https://olivia-games.github.io/seraph/games/ditto/index.html", category: "action", description: "Fast-paced action challenge featuring Ditto." },
  { name: "Feed Me", url: "https://olivia-games.github.io/seraph/games/feedme/index.html", category: "action", description: "React quickly and survive intense action in Feedme." },
  { name: "Final Ninja", url: "https://olivia-games.github.io/seraph/games/finalninja/index.html", category: "action", description: "Finalninja delivers nonstop arcade-style action." },
  { name: "Frostbite", url: "https://olivia-games.github.io/seraph/games/frostbite/index.html", category: "action", description: "Fast-paced action challenge featuring Frostbite." },
  { name: "Frostbite 2", url: "https://olivia-games.github.io/seraph/games/frostbite2/index.html", category: "action", description: "React quickly and survive intense action in Frostbite2." },
  { name: "Icebreaker", url: "https://olivia-games.github.io/seraph/games/icebreaker/index.html", category: "action", description: "Icebreaker delivers nonstop arcade-style action." },
  { name: "Mutiny", url: "https://olivia-games.github.io/seraph/games/mutiny/index.html", category: "action", description: "Fast-paced action challenge featuring Mutiny." },
  { name: "Nitrome Must Die", url: "https://olivia-games.github.io/seraph/games/nitromemustdie/index.html", category: "action", description: "React quickly and survive intense action in Nitromemustdie." },
  { name: "Oodlegobs", url: "https://olivia-games.github.io/seraph/games/oodlegobs/index.html", category: "action", description: "Oodlegobs delivers nonstop arcade-style action." },
  { name: "Super Treadmill", url: "https://olivia-games.github.io/seraph/games/supertreadmill/index.html", category: "action", description: "Fast-paced action challenge featuring Supertreadmill." },
  { name: "Swindler", url: "https://olivia-games.github.io/seraph/games/swindler/index.html", category: "action", description: "React quickly and survive intense action in Swindler." },
  { name: "Test Subject Arena", url: "https://olivia-games.github.io/seraph/games/testsubjectarena/index.html", category: "action", description: "Testsubjectarena delivers nonstop arcade-style action." },
  { name: "Test Subject Complete", url: "https://olivia-games.github.io/seraph/games/testsubjectcomplete/index.html", category: "action", description: "Fast-paced action challenge featuring Testsubjectcomplete." },
  { name: "Twinshot", url: "https://olivia-games.github.io/seraph/games/twinshot/index.html", category: "action", description: "React quickly and survive intense action in Twinshot." },
  { name: "Twinshot 2", url: "https://olivia-games.github.io/seraph/games/twinshot2/index.html", category: "action", description: "Twinshot2 delivers nonstop arcade-style action." },
  { name: "3 Line", url: "https://olivia-games.github.io/seraph/games/3line/index.html", category: "action", description: "Fast-paced action challenge featuring 3line." },
  { name: "Bike Champ", url: "https://olivia-games.github.io/seraph/games/bikechamp/index.html", category: "action", description: "React quickly and survive intense action in Bikechamp." },
  { name: "Bike Champ 2", url: "https://olivia-games.github.io/seraph/games/bikechamp2/index.html", category: "action", description: "Bikechamp2 delivers nonstop arcade-style action." },
  { name: "Corporation Inc.", url: "https://olivia-games.github.io/seraph/games/corporationinc/index.html", category: "action", description: "Fast-paced action challenge featuring Corporationinc." },
  { name: "Shop Empire Fable", url: "https://olivia-games.github.io/seraph/games/shopempirefable/index.html", category: "action", description: "React quickly and survive intense action in Shopempirefable." },
  { name: "Cactus McCoy", url: "https://olivia-games.github.io/seraph/games/cactusmccoy/index.html", category: "action", description: "Cactusmccoy delivers nonstop arcade-style action." },
  { name: "Cactus McCoy 2", url: "https://olivia-games.github.io/seraph/games/cactusmccoy2/index.html", category: "action", description: "Fast-paced action challenge featuring Cactusmccoy2." },
  { name: "Papa Louie", url: "https://olivia-games.github.io/seraph/games/papalouie/index.html", category: "restaurant", description: "Papalouie lets you run your own virtual restaurant." },
  { name: "Papa Louie 2", url: "https://olivia-games.github.io/seraph/games/papalouie2/index.html", category: "restaurant", description: "Prepare meals and satisfy customers in Papalouie2." },
  { name: "Papa Louie 3", url: "https://olivia-games.github.io/seraph/games/papalouie3/index.html", category: "restaurant", description: "Cook, serve, and manage customers in Papalouie3." },
  { name: "Steak and Jake", url: "https://olivia-games.github.io/seraph/games/steakandjake/index.html", category: "action", description: "React quickly and survive intense action in Steakandjake." },
  { name: "Steak and Jake: Midnight March", url: "https://olivia-games.github.io/seraph/games/steakandjakemidnightmarch/index.html", category: "action", description: "Steakandjakemidnightmarch delivers nonstop arcade-style action." },
];
