const GamesData = [
  { name: "Black Jack", url: "https://jasongamesdev.github.io/blackjack/", category: "Action", description: "Gamble away all your money!" },
  { name: "Pink Bike", url: "https://unblocked-games-g.gitlab.io/pinkbike/", category: "Action", description: "Do stunts and rise around hard tracks in pinkbike." },
  { name: "Survival Race", url: "https://rycellgames.github.io/raw/games/racesurvival/index.html", category: "Vehicle", description: "Race through traffic in this high-speed driving challenge." },
  { name: "Geometry Dash", url: "https://web-dashers.github.io", category: "Action", description: "Jump through rhythm-based obstacle courses." },
  { name: "Tung Sahur Horror", url: "https://lanyon-tutoring-help.github.io/tung-sahur-horror", category: "Horror", description: "Survive terrifying encounters in this horror challenge." },
  { name: "Slope", url: "https://olivia-games.github.io/seraph/games/slope/index.html", category: "Action", description: "Roll down an endless 3D slope avoiding obstacles." },
  { name: "Subway Surfers", url: "https://olivia-games.github.io/seraph/games/subwaysurfers/index.html", category: "Action", description: "Dash through subway tracks in this endless runner." },
  { name: "Flappy", url: "https://olivia-games.github.io/seraph/games/flappy/index.html", category: "Action", description: "Navigate a bird through narrow gaps in this arcade game." },
  { name: "Papa's Pizzaria", url: "https://olivia-games.github.io/seraph/games/papaspizzaria/index.html", category: "Multiplayer", description: "Cook and serve pizza to hungry customers." },
  { name: "Papa's Burgeria", url: "https://olivia-games.github.io/seraph/games/papasburgeria/index.html", category: "Multiplayer", description: "Run your own burger restaurant." },
  { name: "Slither.io", url: "https://rycellgames.github.io/raw/games/slitherio/index.html", category: "Multiplayer", description: "Grow your snake by eating orbs online." },
  { name: "Super Mario 64", url: "https://olivia-games.github.io/seraph/games/sm64/index.html", category: "Action", description: "Explore 3D worlds collecting stars." },
  { name: "Run 3", url: "https://olivia-games.github.io/seraph/games/run3/index.html", category: "Parkour", description: "Run through space tunnels performing wall jumps." },
  { name: "Bitlife", url: "https://olivia-games.github.io/seraph/games/bitlife/index.html", category: "Multiplayer", description: "Make life decisions in this text-based simulation." },
  { name: "Crossy Road", url: "https://olivia-games.github.io/seraph/games/crossy/index.html", category: "Action", description: "Hop across roads and rivers in this arcade game." },
  { name: "Minecraft", url: "https://shadownetworkdevs.github.io/", category: "Survival", description: "Build, mine, and survive in this browser sandbox." },
  { name: "Cookie Clicker", url: "https://olivia-games.github.io/seraph/games/cookieclicker/index.html", category: "Multiplayer", description: "Click to bake cookies and build your empire." },
  { name: "Temple Run 2", url: "https://olivia-games.github.io/seraph/games/templerun2/index.html", category: "Action", description: "Run endlessly dodging obstacles in this iconic runner." },
  { name: "Duck Life 4", url: "https://olivia-games.github.io/seraph/games/ducklife4/index.html", category: "Action", description: "Train your duck and compete in races." },
  { name: "Dino Game", url: "https://olivia-games.github.io/seraph/games/dinogame/index.html", category: "Action", description: "Guide a T-Rex jumping over cacti." },
  { name: "Jetpack Joyride", url: "https://olivia-games.github.io/seraph/games/jetpackjoyride/index.html", category: "Action", description: "Fly with a jetpack dodging obstacles." },
  { name: "Retro Bowl", url: "https://olivia-games.github.io/seraph/games/retrobowl/index.html", category: "Multiplayer", description: "Manage and play football games." },
  { name: "Fruit Ninja", url: "https://olivia-games.github.io/seraph/games/fruitninja/index.html", category: "Action", description: "Slice flying fruit while avoiding bombs." },
  { name: "Doodle Jump", url: "https://olivia-games.github.io/seraph/games/doodlejump/index.html", category: "Action", description: "Jump endlessly on platforms in this vertical game." },
  { name: "2048", url: "https://olivia-games.github.io/seraph/games/2048/index.html", category: "Puzzle", description: "Combine tiles to reach 2048 in this puzzle game." },
  { name: "Tetris", url: "https://olivia-games.github.io/seraph/games/tetris/index.html", category: "Puzzle", description: "Arrange falling blocks to clear lines." },
  { name: "Fancy Pants Adventure", url: "https://olivia-games.github.io/seraph/games/fancypantsadventure/index.html", category: "Parkour", description: "Sprint and wall-run as the stickman." },
  { name: "Happy Wheels", url: "https://olivia-games.github.io/seraph/games/happywheels/index.html", category: "Action", description: "Navigate obstacle courses with ragdoll physics." },
  { name: "Papa's Hot Doggeria", url: "https://olivia-games.github.io/seraph/games/papashotdoggeria/index.html", category: "Multiplayer", description: "Serve hot dogs at your fast food restaurant." },
  { name: "Paper.io 2", url: "https://olivia-games.github.io/seraph/games/paperio2/index.html", category: "Multiplayer", description: "Claim territory while avoiding other players." },
  { name: "Super Hot", url: "https://olivia-games.github.io/seraph/games/superhot/index.html", category: "Shooting", description: "Time moves only when you move in this FPS." },
  { name: "The Binding of Isaac", url: "https://olivia-games.github.io/seraph/games/thebindingofisaac/index.html", category: "Survival", description: "Fight through dungeons in this roguelike shooter." },
  { name: "Town Scaper", url: "https://olivia-games.github.io/seraph/games/townscaper/index.html", category: "Multiplayer", description: "Build charming towns on the water." },
  { name: "Tunnel Rush", url: "https://olivia-games.github.io/seraph/games/tunnelrush/index.html", category: "Action", description: "Race through a neon tunnel dodging obstacles." },
  { name: "Theme Hotel", url: "https://olivia-games.github.io/seraph/games/themehotel/index.html", category: "Multiplayer", description: "Manage a hotel and keep guests happy." },
  { name: "Escaping the Prison", url: "https://olivia-games.github.io/seraph/games/escapingtheprison/index.html", category: "Puzzle", description: "Find your way out of maximum security prison." },
  { name: "Stealing the Diamond", url: "https://olivia-games.github.io/seraph/games/stealingthediamond/index.html", category: "Puzzle", description: "Plan and execute a diamond heist." },
  { name: "Infiltrating the Airship", url: "https://olivia-games.github.io/seraph/games/infiltratingtheairship/index.html", category: "Puzzle", description: "Infiltrate an airship and complete your mission." },
  { name: "Fleeing the Complex", url: "https://olivia-games.github.io/seraph/games/fleeingthecomplex/index.html", category: "Puzzle", description: "Escape a secret facility using clever tactics." },
  { name: "The Impossible Quiz", url: "https://olivia-games.github.io/seraph/games/theimpossiblequiz/index.html", category: "Puzzle", description: "Answer tricky questions in this difficult quiz." },
  { name: "Solitaire", url: "https://olivia-games.github.io/seraph/games/solitaire/index.html", category: "Puzzle", description: "Play the classic card game of solitaire." },
  { name: "Moto X3M 2", url: "https://rycellgames.github.io/raw/games/motox3m2/index.html", category: "Vehicle", description: "Perform stunts on motorbike obstacle courses." },
  { name: "Drift Hunters", url: "https://olivia-games.github.io/seraph/games/drifthunters/index.html", category: "Vehicle", description: "Master drifting skills in this racing game." },
  { name: "Vex 6", url: "https://olivia-games.github.io/seraph/games/vex6/index.html", category: "Parkour", description: "Navigate deadly obstacle courses in this platformer." },
  { name: "Among Us", url: "https://olivia-games.github.io/seraph/games/amongus/index.html", category: "Multiplayer", description: "Complete tasks while finding the impostor." },
  { name: "Surf", url: "https://olivia-games.github.io/seraph/games/surf/index.html", category: "Action", description: "Ride waves and perform tricks in this surfing game." },
  { name: "Moto X3M", url: "https://23azostore.github.io/s8/moto-x3m", category: "Vehicle", description: "Race through tracks and perform stunts." },
  { name: "FNAF", url: "https://olivia-games.github.io/seraph/games/fnaf/index.html", category: "Horror", description: "Survive against haunted animatronics at night." },
  { name: "FNAF 2", url: "https://olivia-games.github.io/seraph/games/fnaf-2/index.html", category: "Horror", description: "Face new animatronic horrors in this sequel." },
  { name: "FNAF 3", url: "https://olivia-games.github.io/seraph/games/fnaf-3/index.html", category: "Horror", description: "Survive against a terrifying animatronic." },
  { name: "FNAF 4", url: "https://olivia-games.github.io/seraph/games/fnaf-4/index.html", category: "Horror", description: "Face your fears in this terrifying installment." },
  { name: "Riddle School", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool1/index.html", category: "Puzzle", description: "Find creative ways to escape school." },
  { name: "Riddle School 2", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool2/index.html", category: "Puzzle", description: "Continue the escape adventure with more puzzles." },
  { name: "Riddle School 3", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool3/index.html", category: "Puzzle", description: "Escape the alien-infested school." },
  { name: "Riddle School 4", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool4/index.html", category: "Puzzle", description: "Team up to find a way out of school." },
  { name: "Riddle School 5", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddleschool5/index.html", category: "Puzzle", description: "Face new escape challenges in this sequel." },
  { name: "Riddle School Transfer", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddletransfer/index.html", category: "Puzzle", description: "Join new characters in this spin-off escape game." },
  { name: "Riddle School Transfer 2", url: "https://olivia-games.github.io/seraph/games/riddleschool/riddletransfer2/index.html", category: "Puzzle", description: "Continue the adventure with more puzzles." },
  { name: "Drift Boss", url: "https://olivia-games.github.io/seraph/games/driftboss/index.html", category: "Vehicle", description: "Drift around corners and collect coins." },
  { name: "FNF", url: "https://olivia-games.github.io/seraph/games/fnf/index.html", category: "Multiplayer", description: "Battle opponents in rhythm-based rap battles." },
  { name: "Pac-Man", url: "https://olivia-games.github.io/seraph/games/pacman/index.html", category: "Action", description: "Navigate mazes eating pellets avoiding ghosts." },
  { name: "Papa's Pancakeria", url: "https://olivia-games.github.io/seraph/games/papaspancakeria/index.html", category: "Multiplayer", description: "Cook and serve delicious pancakes." },
  { name: "Rooftop", url: "https://olivia-games.github.io/seraph/games/rooftop/index.html", category: "Parkour", description: "Run across rooftops performing parkour stunts." },
  { name: "Baldi's Basics", url: "https://olivia-games.github.io/seraph/games/baldisbasics/index.html", category: "Horror", description: "Find notebooks and survive the terrifying Baldi." },
  { name: "Bob the Robber 2", url: "https://olivia-games.github.io/seraph/games/bobtherobber2/index.html", category: "Action", description: "Sneak and steal valuables as a master thief." },
  { name: "Minesweeper", url: "https://olivia-games.github.io/seraph/games/minesweeper/index.html", category: "Puzzle", description: "Clear a minefield using logic and deduction." },
  { name: "Pokemon Emerald", url: "https://olivia-games.github.io/seraph/games/pokemonemerald/index.html", category: "Multiplayer", description: "Catch and battle Pokemon in the Hoenn region." },
  { name: "Pokemon Fire Red", url: "https://olivia-games.github.io/seraph/games/pokemonfirered/index.html", category: "Multiplayer", description: "Start your Pokemon journey in Kanto." },
  { name: "Super Mario Bros", url: "https://olivia-games.github.io/seraph/games/supermariobros/index.html", category: "Parkour", description: "Run and jump through classic platforming levels." },
  { name: "Super Mario Kart", url: "https://olivia-games.github.io/seraph/games/supermariokart/index.html", category: "Vehicle", description: "Race with Mario characters in this kart classic." },
  { name: "Super Mario World", url: "https://olivia-games.github.io/seraph/games/supermarioworld/index.html", category: "Parkour", description: "Jump and explore Yoshi's Island in this classic." },
  { name: "There Is No Game", url: "https://olivia-games.github.io/seraph/games/thereisnogame/index.html", category: "Puzzle", description: "Break the fourth wall in this unique puzzle game." },
  { name: "World's Hardest Game", url: "https://olivia-games.github.io/seraph/games/worldshardestgame/index.html", category: "Puzzle", description: "Guide a square through brutal mazes." },
  { name: "Castlevania", url: "https://olivia-games.github.io/seraph/games/castlevania/index.html", category: "Action", description: "Battle through Dracula's castle in this classic." },
  { name: "Donkey Kong", url: "https://olivia-games.github.io/seraph/games/donkeykong/index.html", category: "Action", description: "Climb platforms and dodge barrels." },
  { name: "Dr. Mario", url: "https://olivia-games.github.io/seraph/games/drmario/index.html", category: "Puzzle", description: "Match pills to eliminate viruses." },
  { name: "Metroid", url: "https://olivia-games.github.io/seraph/games/metroid/index.html", category: "Action", description: "Explore alien worlds in this sci-fi platformer." },
  { name: "Super Mario Bros 2", url: "https://olivia-games.github.io/seraph/games/supermariobros2/index.html", category: "Parkour", description: "Pick up and throw enemies in this platformer." },
  { name: "Super Mario Bros 3", url: "https://olivia-games.github.io/seraph/games/supermariobros3/index.html", category: "Parkour", description: "Use power-ups in this iconic NES platformer." },
  { name: "The Legend of Zelda", url: "https://olivia-games.github.io/seraph/games/thelegendofzelda/index.html", category: "Action", description: "Explore dungeons and save Hyrule." },
  { name: "Wario Ware", url: "https://olivia-games.github.io/seraph/games/warioware/index.html", category: "Action", description: "Beat lightning-fast microgames in this party game." },
  { name: "Yoshi's Island", url: "https://olivia-games.github.io/seraph/games/yoshisisland/index.html", category: "Parkour", description: "Guide Yoshi protecting Baby Mario." },
  { name: "Donkey Kong Land", url: "https://olivia-games.github.io/seraph/games/donkeykongland/index.html", category: "Action", description: "Run and jump as Donkey Kong." },
  { name: "Kirby's Dream Land", url: "https://olivia-games.github.io/seraph/games/kirbysdreamland/index.html", category: "Action", description: "Float and inhale enemies as Kirby." },
  { name: "Super Mario Land", url: "https://olivia-games.github.io/seraph/games/supermarioland/index.html", category: "Parkour", description: "Mario's handheld platforming adventure." },
  { name: "Doge Miner", url: "https://olivia-games.github.io/seraph/games/dogeminer/index.html", category: "Multiplayer", description: "Mine Dogecoin and build your empire." },
  { name: "Tanuki Sunset", url: "https://olivia-games.github.io/seraph/games/tanukisunset/index.html", category: "Vehicle", description: "Skateboard through scenic downhill routes." },
  { name: "Aquapark Slides", url: "https://olivia-games.github.io/seraph/games/aquaparkslides/index.html", category: "Action", description: "Slide down water park tracks." },
  { name: "Color Switch", url: "https://olivia-games.github.io/seraph/games/colorswitch/index.html", category: "Action", description: "Tap through rotating colored obstacles." },
  { name: "Papa's Freezeria", url: "https://olivia-games.github.io/seraph/games/papasfreezeria/index.html", category: "Multiplayer", description: "Create ice cream sundaes for customers." },
  { name: "BTD", url: "https://olivia-games.github.io/seraph/games/btd/btd/index.html", category: "Multiplayer", description: "Build towers to pop bloons in this TD game." },
  { name: "BTD 2", url: "https://olivia-games.github.io/seraph/games/btd/btd2/index.html", category: "Multiplayer", description: "Plan tower placements to defend against bloons." },
  { name: "BTD 3", url: "https://olivia-games.github.io/seraph/games/btd/btd3/index.html", category: "Multiplayer", description: "Strategically place towers to pop bloons." },
  { name: "BTD 4", url: "https://olivia-games.github.io/seraph/games/btd/btd4/index.html", category: "Multiplayer", description: "Upgrade towers and survive bloon waves." },
  { name: "Bomberman", url: "https://olivia-games.github.io/seraph/games/bomberman/index.html", category: "Action", description: "Place bombs and blast through walls." },
  { name: "Fire Emblem", url: "https://olivia-games.github.io/seraph/games/fireemblem/index.html", category: "Multiplayer", description: "Command troops in tactical strategy battles." },
  { name: "Ice Climber", url: "https://olivia-games.github.io/seraph/games/iceclimber/index.html", category: "Action", description: "Climb icy mountains avoiding enemies." },
  { name: "Mario Kart Super Circuit", url: "https://olivia-games.github.io/seraph/games/mariokartsupercircuit/index.html", category: "Vehicle", description: "Race through colorful tracks on GBA." },
  { name: "Pokemon Leaf Green", url: "https://olivia-games.github.io/seraph/games/pokemonleafgreen/index.html", category: "Multiplayer", description: "Catch Pokemon through Kanto in this RPG." },
  { name: "Pokemon Ruby", url: "https://olivia-games.github.io/seraph/games/pokemonruby/index.html", category: "Multiplayer", description: "Explore Hoenn in this GBA RPG." },
  { name: "Pokemon Sapphire", url: "https://olivia-games.github.io/seraph/games/pokemonsapphire/index.html", category: "Multiplayer", description: "Discover Pokemon in this Hoenn adventure." },
  { name: "Superstar Saga", url: "https://olivia-games.github.io/seraph/games/superstarsaga/index.html", category: "Action", description: "Join Mario in this RPG adventure." },
  { name: "A Dance of Fire and Ice", url: "https://olivia-games.github.io/seraph/games/adofai/index.html", category: "Action", description: "Keep rhythm between two orbiting planets." },
  { name: "Super Smash Flash", url: "https://olivia-games.github.io/seraph/games/supersmashflash/index.html", category: "Multiplayer", description: "Battle iconic characters in this fighting game." },
  { name: "Super Meat Boy", url: "https://olivia-games.github.io/seraph/games/supermeatboy/index.html", category: "Parkour", description: "Run through brutally difficult levels." },
  { name: "Stickman Hook", url: "https://olivia-games.github.io/seraph/games/stickmanhook/index.html", category: "Parkour", description: "Swing using physics-based grappling mechanics." },
  { name: "Defend the Tank", url: "https://olivia-games.github.io/seraph/games/defendthetank/index.html", category: "Action", description: "Protect your tank from waves of enemies." },
  { name: "Sort the Court", url: "https://olivia-games.github.io/seraph/games/sortthecourt/index.html", category: "Multiplayer", description: "Make decisions to build your kingdom." },
  { name: "This Is the Only Level", url: "https://olivia-games.github.io/seraph/games/thisistheonlylevel/index.html", category: "Puzzle", description: "Complete the same level with different objectives." },
  { name: "Run", url: "https://olivia-games.github.io/seraph/games/run/index.html", category: "Parkour", description: "Run through 3D obstacle courses." },
  { name: "Run 2", url: "https://olivia-games.github.io/seraph/games/run2/index.html", category: "Parkour", description: "Navigate complex 3D platforms in this sequel." },
  { name: "Battleships", url: "https://olivia-games.github.io/seraph/games/battleships/index.html", category: "Multiplayer", description: "Sink enemy ships by guessing locations." },
  { name: "Breaking the Bank", url: "https://olivia-games.github.io/seraph/games/breakingthebank/index.html", category: "Action", description: "Rob a bank using clever tools." },
  { name: "Duck Life", url: "https://olivia-games.github.io/seraph/games/ducklife/index.html", category: "Action", description: "Train your duck to become the fastest." },
  { name: "Duck Life 2", url: "https://olivia-games.github.io/seraph/games/ducklife2/index.html", category: "Action", description: "Train your duck in new skills." },
  { name: "Duck Life 3", url: "https://olivia-games.github.io/seraph/games/ducklife3/index.html", category: "Action", description: "Train ducks and compete in tournaments." },
  { name: "Line Rider", url: "https://olivia-games.github.io/seraph/games/linerider/index.html", category: "Action", description: "Draw tracks for a sledder to ride." },
  { name: "Mario Combat", url: "https://olivia-games.github.io/seraph/games/mariocombat/index.html", category: "Multiplayer", description: "Battle as Mario characters." },
  { name: "Raft Wars 2", url: "https://olivia-games.github.io/seraph/games/raftwars2/index.html", category: "Action", description: "Aim and shoot to defend your raft." },
  { name: "Space Invaders", url: "https://olivia-games.github.io/seraph/games/spaceinvaders/index.html", category: "Shooting", description: "Shoot waves of alien invaders." },
  { name: "Animal Crossing: Wild World", url: "https://olivia-games.github.io/seraph/games/animalcrossingwildworld/index.html", category: "Multiplayer", description: "Live with animal villagers in this simulation." },
  { name: "Mario Kart DS", url: "https://olivia-games.github.io/seraph/games/mariokartds/index.html", category: "Vehicle", description: "Race with Mario characters on DS." },
  { name: "New Super Mario Bros", url: "https://olivia-games.github.io/seraph/games/newsupermariobros/index.html", category: "Parkour", description: "Classic 2D Mario platforming on DS." },
  { name: "Nintendogs", url: "https://olivia-games.github.io/seraph/games/nintendogs/index.html", category: "Multiplayer", description: "Raise and care for virtual puppies." },
  { name: "Super Mario 64 DS", url: "https://olivia-games.github.io/seraph/games/sm64ds/index.html", category: "Action", description: "3D Mario adventure with new characters." },
  { name: "Gun Mayhem", url: "https://olivia-games.github.io/seraph/games/gunmayhem/index.html", category: "Shooting", description: "Battle in 2D arena shooting." },
  { name: "Learn to Fly", url: "https://olivia-games.github.io/seraph/games/learntofly/index.html", category: "Action", description: "Launch a penguin to fly further." },
  { name: "Rooftop 2", url: "https://olivia-games.github.io/seraph/games/rooftop2/index.html", category: "Parkour", description: "Run across rooftops in this parkour sequel." },
  { name: "Fireboy and Watergirl", url: "https://olivia-games.github.io/seraph/games/fireboywatergirl/index.html", category: "Multiplayer", description: "Solve elemental puzzles in cooperative play." },
  { name: "Chibi Knight", url: "https://olivia-games.github.io/seraph/games/chibiknight/index.html", category: "Action", description: "Battle enemies as a tiny knight." },
  { name: "Cluster Rush", url: "https://olivia-games.github.io/seraph/games/clusterrush/index.html", category: "Action", description: "Navigate through clusters of obstacles." },
  { name: "Doodle Defender", url: "https://olivia-games.github.io/seraph/games/doodledefender/index.html", category: "Shooting", description: "Defend your base in this doodle shooter." },
  { name: "Learn to Fly 2", url: "https://olivia-games.github.io/seraph/games/learntofly2/index.html", category: "Action", description: "Build better rockets to fly further." },
  { name: "Papa's Scooperia", url: "https://olivia-games.github.io/seraph/games/papasscooperia/index.html", category: "Multiplayer", description: "Create cookies and ice cream." },
  { name: "Papa's Sushiria", url: "https://olivia-games.github.io/seraph/games/papassushiria/index.html", category: "Multiplayer", description: "Roll and serve sushi to customers." },
  { name: "Papa's Wingeria", url: "https://olivia-games.github.io/seraph/games/papaswingeria/index.html", category: "Multiplayer", description: "Fry and serve chicken wings." },
  { name: "Raft Wars", url: "https://olivia-games.github.io/seraph/games/raftwars/index.html", category: "Action", description: "Launch projectiles to defend your raft." },
  { name: "Unfair Mario", url: "https://olivia-games.github.io/seraph/games/unfairmario/index.html", category: "Parkour", description: "Jump through levels with hidden traps." },
  { name: "Boxing Physics 2", url: "https://olivia-games.github.io/seraph/games/boxingphysics2/index.html", category: "Multiplayer", description: "Box opponents with realistic physics." },
  { name: "Ace Attorney", url: "https://olivia-games.github.io/seraph/games/aceattorney/index.html", category: "Puzzle", description: "Collect evidence and argue in court." },
  { name: "Metal Gear Solid", url: "https://olivia-games.github.io/seraph/games/metalgearsolid/index.html", category: "Action", description: "Sneak through enemy territory." },
  { name: "Mother 3", url: "https://olivia-games.github.io/seraph/games/mother3/index.html", category: "Multiplayer", description: "Embark on a quirky emotional RPG journey." },
  { name: "Pokemon Diamond", url: "https://olivia-games.github.io/seraph/games/pokemondiamond/index.html", category: "Multiplayer", description: "Explore Sinnoh in this DS RPG." },
  { name: "Pokemon Platinum", url: "https://olivia-games.github.io/seraph/games/pokemonplatinum/index.html", category: "Multiplayer", description: "The definitive Sinnoh Pokemon adventure." },
  { name: "Pokemon Soul Silver", url: "https://olivia-games.github.io/seraph/games/pokemonsoulsilver/index.html", category: "Multiplayer", description: "Return to Johto in this DS remake." },
  { name: "Advance Wars", url: "https://olivia-games.github.io/seraph/games/advancewars/index.html", category: "Multiplayer", description: "Lead armies in turn-based tactical warfare." },
  { name: "Banjo Pilot", url: "https://olivia-games.github.io/seraph/games/banjopilot/index.html", category: "Vehicle", description: "Race in planes as Banjo and Kazooie." },
  { name: "Super Monkey Ball Jr.", url: "https://olivia-games.github.io/seraph/games/supermonkeyballjr/index.html", category: "Action", description: "Roll monkeys through obstacle courses." },
  { name: "The Impossible Quiz 2", url: "https://olivia-games.github.io/seraph/games/theimpossiblequiz2/index.html", category: "Puzzle", description: "Answer even more impossible questions." },
  { name: "Papa's Donuteria", url: "https://olivia-games.github.io/seraph/games/papasdonuteria/index.html", category: "Multiplayer", description: "Make and serve delicious donuts." },
  { name: "Fancy Pants Adventure 2", url: "https://olivia-games.github.io/seraph/games/fancypantsadventure2/index.html", category: "Parkour", description: "Fast-paced platforming in this sequel." },
  { name: "Tiny Fishing", url: "https://olivia-games.github.io/seraph/games/tinyfishing/index.html", category: "Action", description: "Cast your line and catch fish." },
  { name: "Big Red Button", url: "https://olivia-games.github.io/seraph/games/bigredbutton/index.html", category: "Action", description: "Push the big red button and discover what happens." },
  { name: "Achievement Unlocked", url: "https://olivia-games.github.io/seraph/games/achievementunlocked/index.html", category: "Action", description: "Collect achievements in this platformer." },
  { name: "Kirby Mass Attack", url: "https://olivia-games.github.io/seraph/games/kirbymassattack/index.html", category: "Action", description: "Control multiple Kirbies on DS." },
  { name: "Sonic Advance", url: "https://olivia-games.github.io/seraph/games/sonicadvance/index.html", category: "Parkour", description: "Play as Sonic in this GBA platformer." },
  { name: "Worms World Party", url: "https://olivia-games.github.io/seraph/games/wormsworldparty/index.html", category: "Multiplayer", description: "Use wacky weapons to defeat enemy worms." },
  { name: "Bad Ice Cream", url: "https://olivia-games.github.io/seraph/games/badicecream/index.html", category: "Action", description: "Collect fruit while avoiding enemies." },
  { name: "Bad Ice Cream 2", url: "https://olivia-games.github.io/seraph/games/badicecream2/index.html", category: "Action", description: "Freeze blocks and collect fruit." },
  { name: "Bad Ice Cream 3", url: "https://olivia-games.github.io/seraph/games/badicecream3/index.html", category: "Action", description: "More frozen puzzle fun in this sequel." },
  { name: "Adventure Capitalist", url: "https://olivia-games.github.io/seraph/games/adventurecapitalist/index.html", category: "Multiplayer", description: "Build businesses in this idle clicker." },
  { name: "Monkey Mart", url: "https://olivia-games.github.io/seraph/games/monkeymart/index.html", category: "Multiplayer", description: "Manage a supermarket as a monkey." },
  { name: "Doom 64", url: "https://olivia-games.github.io/seraph/games/doom64/index.html", category: "Shooting", description: "Fight demonic forces in this FPS." },
  { name: "Banjo-Kazooie", url: "https://olivia-games.github.io/seraph/games/banjokazooie/index.html", category: "Action", description: "Explore worlds collecting jiggies." },
  { name: "Donkey Kong 64", url: "https://olivia-games.github.io/seraph/games/donkeykong64/index.html", category: "Action", description: "Play as multiple Kongs in this platformer." },
  { name: "F-Zero X", url: "https://olivia-games.github.io/seraph/games/fzerox/index.html", category: "Vehicle", description: "Race at breakneck speed on futuristic tracks." },
  { name: "Kirby 64", url: "https://olivia-games.github.io/seraph/games/kirby64/index.html", category: "Action", description: "Combine copy abilities in this 3D Kirby." },
  { name: "Mario Kart 64", url: "https://olivia-games.github.io/seraph/games/mariokart64/index.html", category: "Vehicle", description: "Race through classic tracks on N64." },
  { name: "Mario Party", url: "https://olivia-games.github.io/seraph/games/marioparty/index.html", category: "Multiplayer", description: "Compete in board game mini-games." },
  { name: "Mario Party 2", url: "https://olivia-games.github.io/seraph/games/marioparty2/index.html", category: "Multiplayer", description: "More board game fun with themed levels." },
  { name: "Ocarina of Time", url: "https://olivia-games.github.io/seraph/games/ocarinaoftime/index.html", category: "Action", description: "Save Hyrule in this legendary Zelda." },
  { name: "Star Fox 64", url: "https://olivia-games.github.io/seraph/games/starfox64/index.html", category: "Vehicle", description: "Fly through space in this arcade shooter." },
  { name: "Super Smash Bros", url: "https://olivia-games.github.io/seraph/games/supersmashbros/index.html", category: "Multiplayer", description: "Battle Nintendo characters in this fighter." },
  { name: "Street Fighter 2", url: "https://olivia-games.github.io/seraph/games/streetfighter2/index.html", category: "Multiplayer", description: "Fight as iconic characters in this classic." },
  { name: "Getaway Shootout", url: "https://olivia-games.github.io/seraph/games/getawayshootout/index.html", category: "Shooting", description: "Race to the getaway vehicle shooting opponents." },
  { name: "Rabbit Samurai", url: "https://olivia-games.github.io/seraph/games/rabbitsamurai/index.html", category: "Action", description: "Slice enemies as a rabbit samurai." },
  { name: "Mario Party DS", url: "https://olivia-games.github.io/seraph/games/mariopartyds/index.html", category: "Multiplayer", description: "Play Mario Party on the go." },
  { name: "Professor Layton", url: "https://olivia-games.github.io/seraph/games/professorlayton/index.html", category: "Puzzle", description: "Solve puzzles in this DS adventure." },
  { name: "Scribblenauts", url: "https://olivia-games.github.io/seraph/games/scribblenauts/index.html", category: "Puzzle", description: "Write anything to solve puzzles." },
  { name: "Advance Wars 2", url: "https://olivia-games.github.io/seraph/games/advancewars2/index.html", category: "Multiplayer", description: "Command armies in tactical battles." },
  { name: "Harvest Moon", url: "https://olivia-games.github.io/seraph/games/harvestmoon/index.html", category: "Multiplayer", description: "Farm and build relationships in this sim." },
  { name: "Mario Tennis", url: "https://olivia-games.github.io/seraph/games/mariotennis/index.html", category: "Multiplayer", description: "Play tennis with Mario characters." },
  { name: "Mega Man Zero", url: "https://olivia-games.github.io/seraph/games/megamanzero/index.html", category: "Action", description: "Fight through levels as Zero." },
  { name: "Pokemon Mystery Dungeon", url: "https://olivia-games.github.io/seraph/games/pokemonmysterydungeon/index.html", category: "Multiplayer", description: "Explore dungeons as a Pokemon." },
  { name: "Pokemon Unbound", url: "https://olivia-games.github.io/seraph/games/pokemonunbound/index.html", category: "Multiplayer", description: "Experience a fan-made Pokemon adventure." },
  { name: "Papa's Cheeseria", url: "https://olivia-games.github.io/seraph/games/papascheeseria/index.html", category: "Multiplayer", description: "Make grilled cheese sandwiches." },
  { name: "Papa's Cupcakeria", url: "https://olivia-games.github.io/seraph/games/papascupcakeria/index.html", category: "Multiplayer", description: "Bake and decorate cupcakes." },
  { name: "Papa's Bakeria", url: "https://olivia-games.github.io/seraph/games/papasbakeria/index.html", category: "Multiplayer", description: "Bake pies and cakes." },
  { name: "Papa's Pastaria", url: "https://olivia-games.github.io/seraph/games/papaspastaria/index.html", category: "Multiplayer", description: "Prepare Italian pasta dishes." },
  { name: "Gun Mayhem 2", url: "https://olivia-games.github.io/seraph/games/gunmayhem2/index.html", category: "Shooting", description: "Battle with more weapons and maps." },
  { name: "Gun Mayhem Redux", url: "https://olivia-games.github.io/seraph/games/gunmayhemredux/index.html", category: "Shooting", description: "Improved shooting action in this redux." },
  { name: "Achievement Unlocked 2", url: "https://olivia-games.github.io/seraph/games/achievementunlocked2/index.html", category: "Action", description: "Collect more achievements in this sequel." },
  { name: "Achievement Unlocked 3", url: "https://olivia-games.github.io/seraph/games/achievementunlocked3/index.html", category: "Action", description: "Complete even more challenges." },
  { name: "Factory Balls", url: "https://olivia-games.github.io/seraph/games/factoryballs/index.html", category: "Puzzle", description: "Paint balls with patterns." },
  { name: "Skywire", url: "https://olivia-games.github.io/seraph/games/skywire/index.html", category: "Action", description: "Navigate a cart through sky-high tracks." },
  { name: "Super Mario Flash", url: "https://olivia-games.github.io/seraph/games/supermarioflash/index.html", category: "Parkour", description: "Classic Mario platforming in Flash." },
  { name: "Golden Sun", url: "https://olivia-games.github.io/seraph/games/goldensun/index.html", category: "Multiplayer", description: "Epic RPG adventure with Djinn summoning." },
  { name: "Metroid Fusion", url: "https://olivia-games.github.io/seraph/games/metroidfusion/index.html", category: "Action", description: "Explore space stations in this GBA game." },
  { name: "DBZ Supersonic Warriors", url: "https://olivia-games.github.io/seraph/games/dbzsupersonicwarriors/index.html", category: "Multiplayer", description: "Fight as DBZ characters." },
  { name: "Wario Land 4", url: "https://olivia-games.github.io/seraph/games/warioland4/index.html", category: "Action", description: "Dash and smash through levels as Wario." },
  { name: "Duck Life 5", url: "https://olivia-games.github.io/seraph/games/ducklife5/index.html", category: "Action", description: "Train your duck to become a fighting champion." },
  { name: "Learn to Fly 3", url: "https://olivia-games.github.io/seraph/games/learntofly3/index.html", category: "Action", description: "Build rockets and launch the penguin." },
  { name: "Bloxors", url: "https://olivia-games.github.io/seraph/games/bloxors/index.html", category: "Puzzle", description: "Push blocks to solve isometric puzzles." },
  { name: "Electric Man 2", url: "https://olivia-games.github.io/seraph/games/electricman2/index.html", category: "Multiplayer", description: "Fight using electricity-based attacks." },
  { name: "Portal", url: "https://olivia-games.github.io/seraph/games/portal/index.html", category: "Puzzle", description: "Use portals to solve physics puzzles." },
  { name: "Portal 2", url: "https://olivia-games.github.io/seraph/games/portal2/index.html", category: "Puzzle", description: "More portal-based puzzle solving." },
  { name: "Skywire 2", url: "https://olivia-games.github.io/seraph/games/skywire2/index.html", category: "Action", description: "Navigate treacherous aerial tracks." },
  { name: "Duck Life 6", url: "https://olivia-games.github.io/seraph/games/ducklife6/index.html", category: "Action", description: "Train your duck and explore the world." },
  { name: "Boxing Random", url: "https://olivia-games.github.io/seraph/games/boxingrandom/index.html", category: "Multiplayer", description: "Box opponents in this physics game." },
  { name: "Cell Machine", url: "https://olivia-games.github.io/seraph/games/cellmachine/index.html", category: "Multiplayer", description: "Combine cells to create organisms." },
  { name: "Stickman Boost", url: "https://olivia-games.github.io/seraph/games/stickmanboost/index.html", category: "Parkour", description: "Boost and flip through obstacles." },
  { name: "Vex 3", url: "https://olivia-games.github.io/seraph/games/vex3/index.html", category: "Parkour", description: "Run and jump through obstacle courses." },
  { name: "Vex 4", url: "https://olivia-games.github.io/seraph/games/vex4/index.html", category: "Parkour", description: "More precision platforming in this sequel." },
  { name: "Skibidi 1v100", url: "https://olivia-games.github.io/seraph/games/skibidi1v100/index.html", category: "Action", description: "Survive against waves of enemies." },
  { name: "GoldenEye 007", url: "https://olivia-games.github.io/seraph/games/goldeneye007/index.html", category: "Shooting", description: "Iconic N64 FPS with spy action." },
  { name: "Majora's Mask", url: "https://olivia-games.github.io/seraph/games/majorasmask/index.html", category: "Action", description: "Save Termina with time loops." },
  { name: "Paper Mario", url: "https://olivia-games.github.io/seraph/games/papermario/index.html", category: "Multiplayer", description: "RPG adventure with paper-style visuals." },
  { name: "Mario Golf", url: "https://olivia-games.github.io/seraph/games/mariogolf/index.html", category: "Multiplayer", description: "Play golf with Mario characters." },
  { name: "Pokemon Stadium", url: "https://olivia-games.github.io/seraph/games/pokemonstadium/index.html", category: "Multiplayer", description: "Battle Pokemon in 3D with mini-games." },
  { name: "Excitebike 64", url: "https://olivia-games.github.io/seraph/games/excitebike64/index.html", category: "Vehicle", description: "Perform stunts in this dirt bike racer." },
  { name: "Pokemon Snap", url: "https://olivia-games.github.io/seraph/games/pokemonsnap/index.html", category: "Multiplayer", description: "Take photos of Pokemon in nature." },
  { name: "Mario Party 3", url: "https://olivia-games.github.io/seraph/games/marioparty3/index.html", category: "Multiplayer", description: "More Mario Party with new boards." },
  { name: "Sonic Advance 2", url: "https://olivia-games.github.io/seraph/games/sonicadvance2/index.html", category: "Parkour", description: "Fast Sonic platforming in this sequel." },
  { name: "Bowser's Inside Story", url: "https://olivia-games.github.io/seraph/games/bowsersinsidestory/index.html", category: "Multiplayer", description: "Enter Bowser's body in this RPG." },
  { name: "Spirit Tracks", url: "https://olivia-games.github.io/seraph/games/spirittracks/index.html", category: "Action", description: "Control trains in this Zelda DS game." },
  { name: "The Sims 2", url: "https://olivia-games.github.io/seraph/games/thesims2/index.html", category: "Multiplayer", description: "Manage virtual people's lives." },
  { name: "Tetris DS", url: "https://olivia-games.github.io/seraph/games/tetrisds/index.html", category: "Puzzle", description: "Classic Tetris with Nintendo themes." },
  { name: "Sonic Rush", url: "https://olivia-games.github.io/seraph/games/sonicrush/index.html", category: "Parkour", description: "Fast Sonic platforming on two screens." },
  { name: "The Sims 3", url: "https://olivia-games.github.io/seraph/games/thesims3/index.html", category: "Multiplayer", description: "Life simulation with open worlds." },
  { name: "Super Princess Peach", url: "https://olivia-games.github.io/seraph/games/superprincesspeach/index.html", category: "Action", description: "Control Princess Peach with emotion powers." },
  { name: "Lego Batman", url: "https://olivia-games.github.io/seraph/games/legobatman/index.html", category: "Action", description: "Play as Batman in Lego Gotham City." },
  { name: "Doom 2", url: "https://olivia-games.github.io/seraph/games/doom2/index.html", category: "Shooting", description: "More demon-shooting FPS action." },
  { name: "Duke Nukem Advance", url: "https://olivia-games.github.io/seraph/games/dukenukemadvance/index.html", category: "Shooting", description: "Shoot aliens as Duke Nukem." },
  { name: "Mario Party Advance", url: "https://olivia-games.github.io/seraph/games/mariopartyadvance/index.html", category: "Multiplayer", description: "Play Mario Party mini-games solo." },
  { name: "Mario Pinball Land", url: "https://olivia-games.github.io/seraph/games/mariopinballland/index.html", category: "Multiplayer", description: "Launch Mario in a pinball adventure." },
  { name: "Pac-Man World", url: "https://olivia-games.github.io/seraph/games/pacmanworld/index.html", category: "Action", description: "Pac-Man in 3D platforming levels." },
  { name: "Rayman 3", url: "https://olivia-games.github.io/seraph/games/rayman3/index.html", category: "Action", description: "Platform through colorful levels." },
  { name: "Shrek 2", url: "https://olivia-games.github.io/seraph/games/shrek2/index.html", category: "Action", description: "Play as Shrek characters in this platformer." },
  { name: "SimCity", url: "https://olivia-games.github.io/seraph/games/simcity/index.html", category: "Multiplayer", description: "Build and manage a city." },
  { name: "Simpsons Road Rage", url: "https://olivia-games.github.io/seraph/games/simpsonsroadrage/index.html", category: "Vehicle", description: "Drive through Springfield." },
  { name: "Diddy Kong Racing", url: "https://olivia-games.github.io/seraph/games/diddykongracing/index.html", category: "Vehicle", description: "Race in cars, planes, and hovercrafts." },
  { name: "Wave Race 64", url: "https://olivia-games.github.io/seraph/games/waverace64/index.html", category: "Vehicle", description: "Ride jet skis on dynamic water." },
  { name: "Quest 64", url: "https://olivia-games.github.io/seraph/games/quest64/index.html", category: "Action", description: "Explore a 3D world in this RPG." },
  { name: "Gex 64", url: "https://olivia-games.github.io/seraph/games/gex64/index.html", category: "Action", description: "Platform through TV-themed levels." },
  { name: "Duke Nukem 64", url: "https://olivia-games.github.io/seraph/games/dukenukem64/index.html", category: "Shooting", description: "Shoot aliens in this N64 version." },
  { name: "Mortal Kombat 4", url: "https://olivia-games.github.io/seraph/games/mortalkombat4/index.html", category: "Multiplayer", description: "Fight in brutal 3D combat." },
  { name: "Bad Piggies", url: "https://olivia-games.github.io/seraph/games/badpiggies/index.html", category: "Puzzle", description: "Build contraptions to help pigs." },
  { name: "Super Mario Flash 2", url: "https://olivia-games.github.io/seraph/games/supermarioflash2/index.html", category: "Parkour", description: "More classic Mario platforming." },
  { name: "Swords and Sandals", url: "https://olivia-games.github.io/seraph/games/swordsandsandals/index.html", category: "Multiplayer", description: "Fight as a gladiator in turn-based combat." },
  { name: "Swords and Sandals 2", url: "https://olivia-games.github.io/seraph/games/swordsandsandals2/index.html", category: "Multiplayer", description: "More gladiator combat with upgrades." },
  { name: "Wordle", url: "https://olivia-games.github.io/seraph/games/wordle/index.html", category: "Puzzle", description: "Guess the five-letter word daily." },
  { name: "Vex", url: "https://olivia-games.github.io/seraph/games/vex/index.html", category: "Parkour", description: "The original Vex precision platforming." },
  { name: "Vex 2", url: "https://olivia-games.github.io/seraph/games/vex2/index.html", category: "Parkour", description: "More challenging obstacle courses." },
  { name: "Vex 5", url: "https://olivia-games.github.io/seraph/games/vex5/index.html", category: "Parkour", description: "Even more precision platforming." },
  { name: "Vex 7", url: "https://olivia-games.github.io/seraph/games/vex7/index.html", category: "Parkour", description: "Master difficult platforming challenges." },
  { name: "Stack", url: "https://olivia-games.github.io/seraph/games/stack/index.html", category: "Action", description: "Stack blocks perfectly in this precision game." },
  { name: "Skibidi Toilet Attack", url: "https://olivia-games.github.io/seraph/games/skibiditoiletattack/index.html", category: "Action", description: "Defend against Skibidi Toilets." },
  { name: "Moto X3M Pool", url: "https://rycellgames.github.io/raw/games/motox3m-pool/index.html", category: "Vehicle", description: "Ride through pool-themed obstacle courses." },
  { name: "Offline Paradise", url: "https://olivia-games.github.io/seraph/games/offlineparadise/index.html", category: "Multiplayer", description: "Build and manage a paradise island." },
  { name: "A Link to the Past", url: "https://olivia-games.github.io/seraph/games/linktothepast/index.html", category: "Action", description: "Classic Zelda with light and dark worlds." },
  { name: "Donkey Kong Country", url: "https://olivia-games.github.io/seraph/games/donkeykongcountry/index.html", category: "Parkour", description: "Run through jungle levels in this classic." },
  { name: "Donkey Kong Country 2", url: "https://olivia-games.github.io/seraph/games/donkeykongcountry2/index.html", category: "Parkour", description: "Platform with Diddy and Dixie Kong." },
  { name: "Super Bomberman", url: "https://olivia-games.github.io/seraph/games/superbomberman/index.html", category: "Action", description: "Bomb your way through levels." },
  { name: "Mario Paint", url: "https://olivia-games.github.io/seraph/games/mariopaint/index.html", category: "Multiplayer", description: "Create art and music with Mario." },
  { name: "Mega Man X", url: "https://olivia-games.github.io/seraph/games/megamanx/index.html", category: "Action", description: "Run and gun as Mega Man X." },
  { name: "Super Mario RPG", url: "https://olivia-games.github.io/seraph/games/supermariorpg/index.html", category: "Multiplayer", description: "The first Mario RPG with turn-based battles." },
  { name: "Super Tennis", url: "https://olivia-games.github.io/seraph/games/supertennis/index.html", category: "Multiplayer", description: "Classic tennis gameplay on SNES." },
  { name: "Wario's Woods", url: "https://olivia-games.github.io/seraph/games/warioswoods/index.html", category: "Puzzle", description: "Use bombs to clear blocks as Wario." },
  { name: "World's Hardest Game 2", url: "https://olivia-games.github.io/seraph/games/worldshardestgame2/index.html", category: "Puzzle", description: "Even harder levels in this brutal game." },
  { name: "Bubble Tanks 2", url: "https://olivia-games.github.io/seraph/games/bubbletanks2/index.html", category: "Shooting", description: "Shoot and grow your tank." },
  { name: "Choose Your Weapon", url: "https://olivia-games.github.io/seraph/games/chooseyourweapon/index.html", category: "Multiplayer", description: "Select weapons and fight opponents." },
  { name: "Choose Your Weapon 2", url: "https://olivia-games.github.io/seraph/games/chooseyourweapon2/index.html", category: "Multiplayer", description: "More weapon choices and combat." },
  { name: "Choose Your Weapon 3", url: "https://olivia-games.github.io/seraph/games/chooseyourweapon3/index.html", category: "Multiplayer", description: "Even more weapons and battles." },
  { name: "Connect 4", url: "https://olivia-games.github.io/seraph/games/connect4/index.html", category: "Multiplayer", description: "Connect four discs in a row." },
  { name: "Electric Box", url: "https://olivia-games.github.io/seraph/games/electricbox/index.html", category: "Puzzle", description: "Solve circuit-based puzzles." },
  { name: "MC Tower Defence 2", url: "https://olivia-games.github.io/seraph/games/mctowerdefence2/index.html", category: "Multiplayer", description: "Build towers in Minecraft style." },
  { name: "Cars 2", url: "https://olivia-games.github.io/seraph/games/cars2/index.html", category: "Vehicle", description: "Race as Cars characters." },
  { name: "Cooking Mama", url: "https://olivia-games.github.io/seraph/games/cookingmama/index.html", category: "Multiplayer", description: "Cook dishes in this popular game." },
  { name: "Adventure Time", url: "https://olivia-games.github.io/seraph/games/adventuretime/index.html", category: "Action", description: "Fight as Finn and Jake." },
  { name: "Garfield Gets Real", url: "https://olivia-games.github.io/seraph/games/garfieldgetsreal/index.html", category: "Action", description: "Play as Garfield in this platformer." },
  { name: "WarioWare Touched!", url: "https://olivia-games.github.io/seraph/games/wariowaretouched/index.html", category: "Action", description: "Play touch-based microgames." },
  { name: "Kirby: Power Paintbrush", url: "https://olivia-games.github.io/seraph/games/kirbypowerpaintbrush/index.html", category: "Action", description: "Draw lines to guide Kirby." },
  { name: "Sonic & Knuckles", url: "https://olivia-games.github.io/seraph/games/sonicandknuckles/index.html", category: "Parkour", description: "Play as Sonic and Knuckles." },
  { name: "Altered Beast", url: "https://olivia-games.github.io/seraph/games/alteredbeast/index.html", category: "Action", description: "Transform into beasts in this classic." },
  { name: "Sonic Spinball", url: "https://olivia-games.github.io/seraph/games/sonicspinball/index.html", category: "Parkour", description: "Pinball meets Sonic in this unique game." },
  { name: "Sonic the Hedgehog 3", url: "https://olivia-games.github.io/seraph/games/sonicthehedgehog3/index.html", category: "Parkour", description: "Classic Sonic platforming in this game." },
  { name: "Streets of Rage", url: "https://olivia-games.github.io/seraph/games/streetsofrage/index.html", category: "Action", description: "Beat 'em up action in this classic." },
  { name: "Golden Axe", url: "https://olivia-games.github.io/seraph/games/goldenaxe/index.html", category: "Action", description: "Hack and slash through enemies." },
  { name: "Kirby & the Amazing Mirror", url: "https://olivia-games.github.io/seraph/games/kirbyamazingmirror/index.html", category: "Action", description: "Explore as Kirby in this GBA classic." },
  { name: "Champion Island", url: "https://olivia-games.github.io/seraph/games/championisland/index.html", category: "Action", description: "Compete in various challenges." },
  { name: "Super Mario Construct", url: "https://olivia-games.github.io/seraph/games/supermarioconstruct/index.html", category: "Parkour", description: "Build and play custom Mario levels." },
  { name: "Clicker Heroes", url: "https://olivia-games.github.io/seraph/games/clickerheroes/index.html", category: "Multiplayer", description: "Click to defeat heroes in this idle RPG." },
  { name: "Stair Race 3D", url: "https://olivia-games.github.io/seraph/games/stairrace3d/index.html", category: "Action", description: "Race up stairs in this fast runner." },
  { name: "Slope 2", url: "https://olivia-games.github.io/seraph/games/slope2/index.html", category: "Action", description: "Roll down slopes with new obstacles." },
  { name: "Paper.io 3D", url: "https://olivia-games.github.io/seraph/games/paperio3d/index.html", category: "Multiplayer", description: "Claim territory in 3D." },
  { name: "Moto X3M Spooky", url: "https://rycellgames.github.io/raw/games/motox3m-spooky/index.html", category: "Vehicle", description: "Halloween-themed motorbike racing." },
  { name: "Moto X3M Winter", url: "https://olivia-games.github.io/seraph/games/motox3mwinter/index.html", category: "Vehicle", description: "Winter-themed motorbike racing." },
  { name: "Snake", url: "https://olivia-games.github.io/seraph/games/snake/index.html", category: "Action", description: "Classic Snake game - eat and grow." },
  { name: "Papa's Taco Mia", url: "https://olivia-games.github.io/seraph/games/papastacomia/index.html", category: "Multiplayer", description: "Serve tacos in this restaurant game." },
  { name: "Ovo", url: "https://olivia-games.github.io/seraph/games/ovo/index.html", category: "Parkour", description: "Perform parkour moves in this platformer." },
  { name: "Knife Hit", url: "https://olivia-games.github.io/seraph/games/knifehit/index.html", category: "Action", description: "Throw knives at spinning targets." },
  { name: "Cube Field", url: "https://olivia-games.github.io/seraph/games/cubefield/index.html", category: "Vehicle", description: "Fly through a field of cubes." },
  { name: "Burger and Frights", url: "https://olivia-games.github.io/seraph/games/burgerandfrights/index.html", category: "Multiplayer", description: "Combine burgers with horror elements." },
  { name: "Chess", url: "https://olivia-games.github.io/seraph/games/chess/index.html", category: "Multiplayer", description: "Play the classic strategy board game." },
  { name: "FNF Mid-Fight", url: "https://olivia-games.github.io/seraph/games/fnfmidfight/index.html", category: "Multiplayer", description: "Rhythm battles in this FNF mod." },
  { name: "Thumb Fighter", url: "https://olivia-games.github.io/seraph/games/thumbfighter/index.html", category: "Multiplayer", description: "Fight with your thumbs." },
  { name: "Snow Battle IO", url: "https://olivia-games.github.io/seraph/games/snowbattleio/index.html", category: "Multiplayer", description: "Throw snowballs at other players." },
  { name: "Lazy Jump 3D", url: "https://olivia-games.github.io/seraph/games/lazyjump3d/index.html", category: "Action", description: "Jump and dodge obstacles in this runner." },
  { name: "Go Ball", url: "https://olivia-games.github.io/seraph/games/goball/index.html", category: "Action", description: "Roll a ball through obstacle courses." },
  { name: "Flippy Fish", url: "https://olivia-games.github.io/seraph/games/flippyfish/index.html", category: "Action", description: "Flip a fish through obstacles." },
  { name: "Shop Empire", url: "https://olivia-games.github.io/seraph/games/shopempire/index.html", category: "Multiplayer", description: "Build and manage your shop empire." },
  { name: "Monster Brawl", url: "https://olivia-games.github.io/seraph/games/monsterbrawl/index.html", category: "Multiplayer", description: "Battle as monsters in chaotic combat." },
  { name: "Multitask", url: "https://olivia-games.github.io/seraph/games/multitask/index.html", category: "Action", description: "Perform multiple tasks at once." },
  { name: "Shift", url: "https://olivia-games.github.io/seraph/games/shift/index.html", category: "Puzzle", description: "Shift between black and white." },
  { name: "Shift 2", url: "https://olivia-games.github.io/seraph/games/shift2/index.html", category: "Puzzle", description: "More shifting puzzle action." },
  { name: "Shift 3", url: "https://olivia-games.github.io/seraph/games/shift3/index.html", category: "Puzzle", description: "Even more creative shifting puzzles." },
  { name: "Shift 4", url: "https://olivia-games.github.io/seraph/games/shift4/index.html", category: "Puzzle", description: "Next generation Shift puzzles." },
  { name: "Monopoly", url: "https://olivia-games.github.io/seraph/games/monopoly/index.html", category: "Multiplayer", description: "Buy and trade properties in this board game." },
  { name: "Picross DS", url: "https://olivia-games.github.io/seraph/games/picrossds/index.html", category: "Puzzle", description: "Solve picture-based number puzzles." },
  { name: "WarioWare D.I.Y.", url: "https://olivia-games.github.io/seraph/games/wariowarediy/index.html", category: "Action", description: "Create your own microgames." },
  { name: "Pizza Tower", url: "https://olivia-games.github.io/seraph/games/pizzatower/index.html", category: "Action", description: "Fast-paced action in this platformer." },
  { name: "Territorial IO", url: "https://olivia-games.github.io/seraph/games/territorialio/index.html", category: "Multiplayer", description: "Capture territory in this IO game." },
  { name: "1v1 LOL", url: "https://olivia-games.github.io/seraph/games/1v1lol/index.html", category: "Shooting", description: "Build and battle in this online shooter." },
  { name: "Ballistic Chickens", url: "https://olivia-games.github.io/seraph/games/ballisticchickens/index.html", category: "Action", description: "Launch chickens at targets." },
  { name: "Basket Bros IO", url: "https://olivia-games.github.io/seraph/games/basketbrosio/index.html", category: "Multiplayer", description: "Play basketball against others." },
  { name: "MC Classic", url: "https://olivia-games.github.io/seraph/games/mcclassic/index.html", category: "Action", description: "Classic Minecraft gameplay in browser." },
  { name: "Death Run 3D", url: "https://olivia-games.github.io/seraph/games/deathrun3d/index.html", category: "Action", description: "Run through deadly 3D obstacles." },
  { name: "Soccer Random", url: "https://olivia-games.github.io/seraph/games/soccerrandom/index.html", category: "Multiplayer", description: "Random soccer matches with physics." },
  { name: "Sprinter", url: "https://olivia-games.github.io/seraph/games/sprinter/index.html", category: "Action", description: "Sprint through levels dodging obstacles." },
  { name: "Tron", url: "https://olivia-games.github.io/seraph/games/tron/index.html", category: "Action", description: "Classic light cycle game from Tron." },
  { name: "1 on 1 Soccer", url: "https://olivia-games.github.io/seraph/games/1on1soccer/index.html", category: "Multiplayer", description: "One-on-one soccer matches." },
  { name: "Bad Time Simulator", url: "https://olivia-games.github.io/seraph/games/badtimesimulator/index.html", category: "Action", description: "The famous Sans battle from Undertale." },
  { name: "Amazing Rope Police", url: "https://olivia-games.github.io/seraph/games/amazingropepolice/index.html", category: "Action", description: "Use a rope to capture criminals." },
  { name: "Celeste", url: "https://olivia-games.github.io/seraph/games/celeste/index.html", category: "Parkour", description: "The indie platforming masterpiece." },
  { name: "Just Fall LOL", url: "https://olivia-games.github.io/seraph/games/justfalllol/index.html", category: "Multiplayer", description: "Push other players off platforms." },
  { name: "N-Gon", url: "https://olivia-games.github.io/seraph/games/ngon/index.html", category: "Action", description: "Shoot and survive in this action game." },
  { name: "Rocket Soccer", url: "https://olivia-games.github.io/seraph/games/rocketsoccer/index.html", category: "Vehicle", description: "Rocket-powered car soccer." },
  { name: "Stickman Climb", url: "https://olivia-games.github.io/seraph/games/stickmanclimb/index.html", category: "Parkour", description: "Climb walls as a stickman." },
  { name: "Osu! Mania", url: "https://olivia-games.github.io/seraph/games/osumania/index.html", category: "Multiplayer", description: "Rhythm game with falling notes." },
  { name: "Helix Jump", url: "https://olivia-games.github.io/seraph/games/helixjump/index.html", category: "Action", description: "Guide a ball down a helix tower." },
  { name: "Dadish", url: "https://olivia-games.github.io/seraph/games/dadish/index.html", category: "Parkour", description: "Platforming as a radish dad." },
  { name: "Dadish 2", url: "https://olivia-games.github.io/seraph/games/dadish2/index.html", category: "Parkour", description: "More radish dad platforming." },
  { name: "Dadish 3", url: "https://olivia-games.github.io/seraph/games/dadish3/index.html", category: "Parkour", description: "The third Dadish platformer." },
  { name: "Snow Rider 3D", url: "https://olivia-games.github.io/seraph/games/snowrider3d/index.html", category: "Vehicle", description: "Ride a snowboard through obstacles." },
  { name: "Tube Jumpers", url: "https://olivia-games.github.io/seraph/games/tubejumpers/index.html", category: "Action", description: "Jump through tubes collecting coins." },
  { name: "Yohoho", url: "https://olivia-games.github.io/seraph/games/yohoho/index.html", category: "Multiplayer", description: "Pirate-themed IO treasure game." },
  { name: "10 Minutes Till Dawn", url: "https://olivia-games.github.io/seraph/games/10minutestilldawn/index.html", category: "Survival", description: "Survive waves of monsters." },
  { name: "Volley Random", url: "https://olivia-games.github.io/seraph/games/volleyrandom/index.html", category: "Multiplayer", description: "Physics-based volleyball with randomness." },
  { name: "Waterworks", url: "https://olivia-games.github.io/seraph/games/waterworks/index.html", category: "Puzzle", description: "Connect water sources in this puzzle." },
  { name: "Geometry Rash", url: "https://olivia-games.github.io/seraph/games/geometryrash/index.html", category: "Parkour", description: "Geometry Dash-style platforming." },
  { name: "Hole IO", url: "https://olivia-games.github.io/seraph/games/holeio/index.html", category: "Multiplayer", description: "Swallow objects with a hole." },
  { name: "Sandtrix", url: "https://olivia-games.github.io/seraph/games/sandtrix/index.html", category: "Puzzle", description: "Sand physics with Tetris gameplay." },
  { name: "Shape Shipper", url: "https://olivia-games.github.io/seraph/games/shapeshipper/index.html", category: "Action", description: "Ship shapes and match colors." },
  { name: "Slope Ball", url: "https://olivia-games.github.io/seraph/games/slopeball/index.html", category: "Action", description: "Roll a ball down slopes." },
  { name: "Stickman Golf", url: "https://olivia-games.github.io/seraph/games/stickmangolf/index.html", category: "Multiplayer", description: "Play golf as a stickman." },
  { name: "TABS", url: "https://olivia-games.github.io/seraph/games/tabs/index.html", category: "Multiplayer", description: "Totally Accurate Battle Simulator." },
  { name: "Watermelon Game", url: "https://olivia-games.github.io/seraph/games/watermelongame/index.html", category: "Puzzle", description: "Merge fruits to grow the biggest." },
  { name: "Wall Smash", url: "https://olivia-games.github.io/seraph/games/wallsmash/index.html", category: "Action", description: "Smash through walls in this action game." },
  { name: "Crimson Fantasia", url: "https://olivia-games.github.io/seraph/games/crimsonfantasia/index.html", category: "Action", description: "Platforming with blood-red visuals." },
  { name: "Cut the Rope", url: "https://olivia-games.github.io/seraph/games/cuttherope/index.html", category: "Puzzle", description: "Cut ropes to feed Om Nom candy." },
  { name: "Funny Mad Racing", url: "https://olivia-games.github.io/seraph/games/funnymadracing/index.html", category: "Vehicle", description: "Crazy racing with funny physics." },
  { name: "GD Lite", url: "https://olivia-games.github.io/seraph/games/gdlite/index.html", category: "Action", description: "Lighter version of Geometry Dash." },
  { name: "Grand Theft Grotto", url: "https://olivia-games.github.io/seraph/games/grandtheftgrotto/index.html", category: "Action", description: "GTA-style gameplay in browser." },
  { name: "Drift Mania", url: "https://olivia-games.github.io/seraph/games/driftmania/index.html", category: "Vehicle", description: "Master drifting skills in this racer." },
  { name: "Rise Higher", url: "https://olivia-games.github.io/seraph/games/risehigher/index.html", category: "Action", description: "Jump and rise higher in this game." },
  { name: "Burrito Bison", url: "https://olivia-games.github.io/seraph/games/burritobison/index.html", category: "Action", description: "Launch a bison through grocery stores." },
  { name: "Pool", url: "https://olivia-games.github.io/seraph/games/pool/index.html", category: "Multiplayer", description: "Classic pool with realistic physics." },
  { name: "Red Ball 1", url: "https://olivia-games.github.io/seraph/games/redball1/index.html", category: "Parkour", description: "Roll a red ball through levels." },
  { name: "Red Ball 3", url: "https://olivia-games.github.io/seraph/games/redball3/index.html", category: "Parkour", description: "More red ball platforming." },
  { name: "Red Ball 4", url: "https://olivia-games.github.io/seraph/games/redball4/index.html", category: "Parkour", description: "Advanced red ball platforming." },
  { name: "Red Ball V2", url: "https://olivia-games.github.io/seraph/games/redballv2/index.html", category: "Parkour", description: "Red ball with enhanced physics." },
  { name: "Red Ball V3", url: "https://olivia-games.github.io/seraph/games/redballv3/index.html", category: "Parkour", description: "Even more red ball adventures." },
  { name: "Rough Dino", url: "https://olivia-games.github.io/seraph/games/roughdino/index.html", category: "Action", description: "Play as a rough dinosaur." },
  { name: "Time Shooter 1", url: "https://olivia-games.github.io/seraph/games/timeshooter1/index.html", category: "Shooting", description: "Shoot in slow-motion time manipulation." },
  { name: "Time Shooter 2", url: "https://olivia-games.github.io/seraph/games/timeshooter2/index.html", category: "Shooting", description: "Time-based shooting action sequel." },
  { name: "Time Shooter 3", url: "https://olivia-games.github.io/seraph/games/timeshooter3/index.html", category: "Shooting", description: "Third time-manipulation shooter." },
  { name: "Battletoads", url: "https://olivia-games.github.io/seraph/games/battletoads/index.html", category: "Action", description: "Classic Battletoads beat 'em up." },
  { name: "Castlevania III", url: "https://olivia-games.github.io/seraph/games/castlevaniaiii/index.html", category: "Action", description: "Classic Castlevania with multiple characters." },
  { name: "Contra", url: "https://olivia-games.github.io/seraph/games/contra/index.html", category: "Shooting", description: "Classic Contra run-and-gun action." },
  { name: "DuckTales", url: "https://olivia-games.github.io/seraph/games/ducktales/index.html", category: "Action", description: "Scrooge McDuck's platforming adventure." },
  { name: "Kid Icarus", url: "https://olivia-games.github.io/seraph/games/kidicarus/index.html", category: "Action", description: "Classic Kid Icarus action-platformer." },
  { name: "Mega Man 2", url: "https://olivia-games.github.io/seraph/games/megaman2/index.html", category: "Shooting", description: "Legendary Mega Man 2 run-and-gun." },
  { name: "Ninja Gaiden", url: "https://olivia-games.github.io/seraph/games/ninjagaiden/index.html", category: "Action", description: "Classic Ninja Gaiden action-platformer." },
  { name: "Punch-Out!!", url: "https://olivia-games.github.io/seraph/games/punchout/index.html", category: "Multiplayer", description: "Classic boxing game with memorable opponents." },
  { name: "Chrono Trigger", url: "https://olivia-games.github.io/seraph/games/chronotrigger/index.html", category: "Multiplayer", description: "Legendary time-traveling RPG masterpiece." },
  { name: "Contra III", url: "https://olivia-games.github.io/seraph/games/contraiii/index.html", category: "Shooting", description: "Contra III: The Alien Wars action." },
  { name: "Donkey Kong Country 3", url: "https://olivia-games.github.io/seraph/games/donkeykongcountry3/index.html", category: "Parkour", description: "Third DKC with Dixie and Kiddy." },
  { name: "EarthBound", url: "https://olivia-games.github.io/seraph/games/earthbound/index.html", category: "Multiplayer", description: "Quirky cult classic SNES RPG." },
  { name: "Final Fantasy VI", url: "https://olivia-games.github.io/seraph/games/finalfantasyvi/index.html", category: "Multiplayer", description: "Iconic Final Fantasy VI RPG masterpiece." },
  { name: "F-Zero", url: "https://olivia-games.github.io/seraph/games/fzero/index.html", category: "Vehicle", description: "Original F-Zero futuristic racing." },
  { name: "Super Metroid", url: "https://olivia-games.github.io/seraph/games/supermetroid/index.html", category: "Action", description: "Legendary Super Metroid action-adventure." },
  { name: "Banjo-Tooie", url: "https://olivia-games.github.io/seraph/games/banjotooie/index.html", category: "Action", description: "Second Banjo 3D platforming adventure." },
  { name: "Harvest Moon 64", url: "https://olivia-games.github.io/seraph/games/harvestmoon64/index.html", category: "Multiplayer", description: "Classic Harvest Moon farming on N64." },
  { name: "Jet Force Gemini", url: "https://olivia-games.github.io/seraph/games/jetforcegemini/index.html", category: "Shooting", description: "Third-person shooting in Jet Force Gemini." },
  { name: "Mystical Ninja", url: "https://olivia-games.github.io/seraph/games/mysticalninja/index.html", category: "Action", description: "Action-adventure with giant robot battles." },
  { name: "Turok: Dinosaur Hunter", url: "https://olivia-games.github.io/seraph/games/turokdinosaurhunter/index.html", category: "Shooting", description: "Hunt dinosaurs in this N64 FPS." },
  { name: "Yoshi's Story", url: "https://olivia-games.github.io/seraph/games/yoshisstory/index.html", category: "Parkour", description: "Yoshi's platforming adventure." },
  { name: "Kirby's Dream Land 2", url: "https://olivia-games.github.io/seraph/games/kirbysdreamland2/index.html", category: "Action", description: "Second Kirby with animal friends." },
  { name: "Link's Awakening DX", url: "https://olivia-games.github.io/seraph/games/linksawakeningdx/index.html", category: "Action", description: "Zelda: Link's Awakening for GBC." },
  { name: "Metroid II", url: "https://olivia-games.github.io/seraph/games/metroidii/index.html", category: "Action", description: "Samus's adventure on SR388." },
  { name: "Super Mario Land 2", url: "https://olivia-games.github.io/seraph/games/supermarioland2/index.html", category: "Parkour", description: "Mario's sequel with Wario as villain." },
  { name: "Wario Land II", url: "https://olivia-games.github.io/seraph/games/wariolandii/index.html", category: "Action", description: "Second Wario Land platforming adventure." },
  { name: "Castlevania: Aria of Sorrow", url: "https://olivia-games.github.io/seraph/games/castlevaniaariaofsorrow/index.html", category: "Action", description: "Classic Castlevania: Aria of Sorrow." },
  { name: "Final Fantasy Tactics Advance", url: "https://olivia-games.github.io/seraph/games/finalfantasytacticsadvance/index.html", category: "Multiplayer", description: "Final Fantasy Tactics Advance RPG." },
  { name: "Drill Dozer", url: "https://olivia-games.github.io/seraph/games/drilldozer/index.html", category: "Action", description: "Drill through levels in this GBA game." },
  { name: "Advance Wars: Days of Ruin", url: "https://olivia-games.github.io/seraph/games/advancewarsdayofruin/index.html", category: "Multiplayer", description: "Darker Advance Wars strategy game." },
  { name: "Castlevania: Dawn of Sorrow", url: "https://olivia-games.github.io/seraph/games/castlevaniadawnofsorrow/index.html", category: "Action", description: "Castlevania on DS with touchscreen." },
  { name: "Castlevania: Order of Ecclesia", url: "https://olivia-games.github.io/seraph/games/castlevaniaorderofecclesia/index.html", category: "Action", description: "Third Castlevania DS action-adventure." },
  { name: "Mario & Luigi: Partners in Time", url: "https://olivia-games.github.io/seraph/games/marioandluigipartnersintime/index.html", category: "Multiplayer", description: "Time-traveling RPG on DS." },
  { name: "Comix Zone", url: "https://olivia-games.github.io/seraph/games/comixzone/index.html", category: "Action", description: "Comic book style beat 'em up." },
  { name: "Ecco the Dolphin", url: "https://olivia-games.github.io/seraph/games/eccothedolphin/index.html", category: "Action", description: "Underwater adventure as Ecco." },
  { name: "Gunstar Heroes", url: "https://olivia-games.github.io/seraph/games/gunstarheroes/index.html", category: "Shooting", description: "Classic run-and-gun Gunstar Heroes." },
  { name: "Phantasy Star IV", url: "https://olivia-games.github.io/seraph/games/phantasystariv/index.html", category: "Multiplayer", description: "Classic Phantasy Star IV RPG." },
  { name: "Ranger X", url: "https://olivia-games.github.io/seraph/games/rangerx/index.html", category: "Shooting", description: "Mecha action shooting on Genesis." },
  { name: "Ristar", url: "https://olivia-games.github.io/seraph/games/ristar/index.html", category: "Parkour", description: "Charming Ristar platformer on Genesis." },
  { name: "Shining Force", url: "https://olivia-games.github.io/seraph/games/shiningforce/index.html", category: "Multiplayer", description: "Classic Shining Force strategy RPG." },
  { name: "Shinobi III", url: "https://olivia-games.github.io/seraph/games/shinobiiii/index.html", category: "Action", description: "Classic Shinobi III action on Genesis." },
  { name: "Sonic the Hedgehog", url: "https://olivia-games.github.io/seraph/games/sonicthehedgehog/index.html", category: "Parkour", description: "Original Sonic on Sega Genesis." },
  { name: "Sonic the Hedgehog 2", url: "https://olivia-games.github.io/seraph/games/sonicthehedgehog2/index.html", category: "Parkour", description: "Sonic 2 with Tails." },
  { name: "Streets of Rage 2", url: "https://olivia-games.github.io/seraph/games/streetsofrage2/index.html", category: "Action", description: "Classic Streets of Rage 2 beat 'em up." },
  { name: "Vectorman", url: "https://olivia-games.github.io/seraph/games/vectorman/index.html", category: "Shooting", description: "Vector graphics shooting in Vectorman." },
  { name: "Vectorman 2", url: "https://olivia-games.github.io/seraph/games/vectorman2/index.html", category: "Shooting", description: "Sequel to vector shooting classic." },
  { name: "Illusion of Gaia", url: "https://olivia-games.github.io/seraph/games/illusionofgaia/index.html", category: "Action", description: "Classic Illusion of Gaia action RPG." },
  { name: "Pokemon Yellow", url: "https://olivia-games.github.io/seraph/games/pokemonyellow/index.html", category: "Multiplayer", description: "Pokemon Yellow with Pikachu." },
  { name: "Abuda the Alien", url: "https://olivia-games.github.io/seraph/games/abudathealien/index.html", category: "Action", description: "Alien platforming action." },
  { name: "Battle Beavers", url: "https://olivia-games.github.io/seraph/games/battlebeavers/index.html", category: "Action", description: "Beaver combat action." },
  { name: "Control Craft 2", url: "https://olivia-games.github.io/seraph/games/controlcraft2/index.html", category: "Action", description: "Strategic control craft action." },
  { name: "Age of War", url: "https://olivia-games.github.io/seraph/games/ageofwar/index.html", category: "Multiplayer", description: "Advance through ages in this strategy game." },
  { name: "Age of War 2", url: "https://olivia-games.github.io/seraph/games/ageofwar2/index.html", category: "Multiplayer", description: "Sequel to Age of War strategy." },
  { name: "Amorphous", url: "https://olivia-games.github.io/seraph/games/amorphous/index.html", category: "Action", description: "Survive against blobs." },
  { name: "Bubble Spinner", url: "https://olivia-games.github.io/seraph/games/bubblespinner/index.html", category: "Puzzle", description: "Spin and match bubbles." },
  { name: "Crush the Castle", url: "https://olivia-games.github.io/seraph/games/crushthecastle/index.html", category: "Action", description: "Demolish castles in this physics game." },
  { name: "Crush the Castle 2", url: "https://olivia-games.github.io/seraph/games/crushthecastle2/index.html", category: "Action", description: "More castle destruction in this sequel." },
  { name: "Epic Battle Fantasy", url: "https://olivia-games.github.io/seraph/games/epicbattlefantasy/index.html", category: "Multiplayer", description: "First Epic Battle Fantasy RPG." },
  { name: "Epic Battle Fantasy 2", url: "https://olivia-games.github.io/seraph/games/epicbattlefantasy2/index.html", category: "Multiplayer", description: "Second Epic Battle Fantasy RPG." },
  { name: "Epic Battle Fantasy 3", url: "https://olivia-games.github.io/seraph/games/epicbattlefantasy3/index.html", category: "Multiplayer", description: "Third Epic Battle Fantasy RPG." },
  { name: "Fancy Pants Adventure 3", url: "https://olivia-games.github.io/seraph/games/fancypantsadventure3/index.html", category: "Parkour", description: "Third Fancy Pants platforming adventure." },
  { name: "Flood Runner 2", url: "https://olivia-games.github.io/seraph/games/floodrunner2/index.html", category: "Parkour", description: "Run from floods in this sequel." },
  { name: "Flood Runner 3", url: "https://olivia-games.github.io/seraph/games/floodrunner3/index.html", category: "Parkour", description: "Third flood running platformer." },
  { name: "Dragon Boy 2", url: "https://olivia-games.github.io/seraph/games/dragonboy2/index.html", category: "Action", description: "Dragon action in this sequel." },
  { name: "Neon Rider", url: "https://olivia-games.github.io/seraph/games/neonrider/index.html", category: "Vehicle", description: "Neon motorcycle racing." },
  { name: "Pandemic 2", url: "https://olivia-games.github.io/seraph/games/pandemic2/index.html", category: "Multiplayer", description: "Disease spreading strategy game." },
  { name: "Stick War", url: "https://olivia-games.github.io/seraph/games/stickwar/index.html", category: "Multiplayer", description: "Command stickman armies." },
  { name: "Stick War 2", url: "https://olivia-games.github.io/seraph/games/stickwar2/index.html", category: "Multiplayer", description: "Second Stick War strategy game." },
  { name: "Ultimate Flash Sonic", url: "https://olivia-games.github.io/seraph/games/ultimateflashsonic/index.html", category: "Parkour", description: "Sonic platforming in Flash." },
  { name: "Zombocalypse", url: "https://olivia-games.github.io/seraph/games/zombocalypse/index.html", category: "Shooting", description: "Fight zombies in this action game." },
  { name: "Zombotron", url: "https://olivia-games.github.io/seraph/games/zombotron/index.html", category: "Shooting", description: "Zombie shooting in Zombotron." },
  { name: "Zombotron 2", url: "https://olivia-games.github.io/seraph/games/zombotron2/index.html", category: "Shooting", description: "More zombie shooting in this sequel." },
  { name: "Backrooms 2D", url: "https://olivia-games.github.io/seraph/games/backrooms2d/index.html", category: "Horror", description: "Navigate eerie yellow Backrooms corridors." },
  { name: "Basket Random", url: "https://olivia-games.github.io/seraph/games/basketrandom/index.html", category: "Multiplayer", description: "Random basketball matches." },
  { name: "CSGO Clicker", url: "https://olivia-games.github.io/seraph/games/csgoclicker/index.html", category: "Multiplayer", description: "CSGO-themed clicker game." },
  { name: "Doom", url: "https://olivia-games.github.io/seraph/games/doom/index.html", category: "Shooting", description: "Legendary Doom FPS in browser." },
  { name: "Funny Shooter 2", url: "https://olivia-games.github.io/seraph/games/funnyshooter2/index.html", category: "Shooting", description: "Comedic shooting action." },
  { name: "Gunfest", url: "https://olivia-games.github.io/seraph/games/gunfest/index.html", category: "Shooting", description: "Gun-based fighting action." },
  { name: "Infinite Craft", url: "https://olivia-games.github.io/seraph/games/infinitecraft/index.html", category: "Multiplayer", description: "Craft and combine elements infinitely." },
  { name: "Lows Adventures 2", url: "https://olivia-games.github.io/seraph/games/lowsadventures2/index.html", category: "Action", description: "More adventure action in this sequel." },
  { name: "Pako Highway", url: "https://olivia-games.github.io/seraph/games/pakohighway/index.html", category: "Vehicle", description: "Highway driving action." },
  { name: "Recoil", url: "https://olivia-games.github.io/seraph/games/recoil/index.html", category: "Shooting", description: "Shooting with realistic recoil." },
  { name: "Run 3 Plus", url: "https://olivia-games.github.io/seraph/games/run3plus/index.html", category: "Parkour", description: "Enhanced Run 3 platforming." },
  { name: "Slope City", url: "https://olivia-games.github.io/seraph/games/slopecity/index.html", category: "Action", description: "City-based slope rolling." },
  { name: "State IO", url: "https://olivia-games.github.io/seraph/games/stateio/index.html", category: "Multiplayer", description: "Capture states in this IO game." },
  { name: "Sudoku", url: "https://olivia-games.github.io/seraph/games/sudoku/index.html", category: "Puzzle", description: "Classic Sudoku number puzzle." },
  { name: "Superhero Drop", url: "https://olivia-games.github.io/seraph/games/superherodrop/index.html", category: "Action", description: "Heroic action in this dropping game." },
  { name: "Balloon Run", url: "https://olivia-games.github.io/seraph/games/balloonrun/index.html", category: "Action", description: "Run and collect balloons." },
  { name: "Crazy Tunnel 3D", url: "https://olivia-games.github.io/seraph/games/crazytunnel3d/index.html", category: "Vehicle", description: "3D tunnel racing action." },
  { name: "Eagler 1.8", url: "https://olivia-games.github.io/seraph/games/eagler1.8/index.html", category: "Action", description: "Minecraft client-based gameplay." },
  { name: "Geometry Dash Sky", url: "https://olivia-games.github.io/seraph/games/geometrydashsky/index.html", category: "Action", description: "Sky-themed Geometry Dash." },
  { name: "Wubzzy's Amazing Adventure", url: "https://olivia-games.github.io/seraph/games/wubzzysamazingadventure/index.html", category: "Action", description: "Adventure with Wubzzy." },
  { name: "Gold Digger FRVR", url: "https://olivia-games.github.io/seraph/games/golddiggerfrvr/index.html", category: "Action", description: "Gold digging adventure." },
  { name: "HexGL", url: "https://olivia-games.github.io/seraph/games/hexgl/index.html", category: "Vehicle", description: "Hexagonal racing game." },
  { name: "House of Hazards", url: "https://olivia-games.github.io/seraph/games/houseofhazards/index.html", category: "Multiplayer", description: "Navigate dangerous houses." },
  { name: "Pickcrafter", url: "https://olivia-games.github.io/seraph/games/pickcrafter/index.html", category: "Multiplayer", description: "Pickaxe mining and crafting." },
  { name: "Precision Client", url: "https://olivia-games.github.io/seraph/games/precisionclient/index.html", category: "Action", description: "Precision action gameplay." },
  { name: "Subway Runner", url: "https://olivia-games.github.io/seraph/games/subwayrunner/index.html", category: "Action", description: "Run through subway tracks." },
  { name: "XX142 B2.EXE", url: "https://olivia-games.github.io/seraph/games/xx142-b2.exe/index.html", category: "Action", description: "Action with unique mechanics." },
  { name: "Canopy", url: "https://olivia-games.github.io/seraph/games/canopy/index.html", category: "Action", description: "Canopy-based action gameplay." },
  { name: "Cave Chaos", url: "https://olivia-games.github.io/seraph/games/cavechaos/index.html", category: "Action", description: "Chaotic cave adventure." },
  { name: "Change Type", url: "https://olivia-games.github.io/seraph/games/changetype/index.html", category: "Action", description: "Type-changing action game." },
  { name: "Cheese Dreams", url: "https://olivia-games.github.io/seraph/games/cheesedreams/index.html", category: "Action", description: "Cheese-themed dream adventure." },
  { name: "Chisel", url: "https://olivia-games.github.io/seraph/games/chisel/index.html", category: "Action", description: "Chiseling action game." },
  { name: "Chisel 2", url: "https://olivia-games.github.io/seraph/games/chisel2/index.html", category: "Action", description: "Sequel to Chisel action." },
  { name: "Ditto", url: "https://olivia-games.github.io/seraph/games/ditto/index.html", category: "Action", description: "Mimicking action game." },
  { name: "Feed Me", url: "https://olivia-games.github.io/seraph/games/feedme/index.html", category: "Action", description: "Feed creatures in this action game." },
  { name: "Final Ninja", url: "https://olivia-games.github.io/seraph/games/finalninja/index.html", category: "Action", description: "Ninja action game." },
  { name: "Frostbite", url: "https://olivia-games.github.io/seraph/games/frostbite/index.html", category: "Action", description: "Frosty action gameplay." },
  { name: "Frostbite 2", url: "https://olivia-games.github.io/seraph/games/frostbite2/index.html", category: "Action", description: "Sequel to Frostbite action." },
  { name: "Icebreaker", url: "https://olivia-games.github.io/seraph/games/icebreaker/index.html", category: "Action", description: "Ice-breaking action." },
  { name: "Mutiny", url: "https://olivia-games.github.io/seraph/games/mutiny/index.html", category: "Action", description: "Mutiny action adventure." },
  { name: "Nitrome Must Die", url: "https://olivia-games.github.io/seraph/games/nitromemustdie/index.html", category: "Action", description: "Nitrome action game." },
  { name: "Oodlegobs", url: "https://olivia-games.github.io/seraph/games/oodlegobs/index.html", category: "Action", description: "Oodlegobs action gameplay." },
  { name: "Super Treadmill", url: "https://olivia-games.github.io/seraph/games/supertreadmill/index.html", category: "Action", description: "Treadmill-based action." },
  { name: "Swindler", url: "https://olivia-games.github.io/seraph/games/swindler/index.html", category: "Action", description: "Swindling action adventure." },
  { name: "Test Subject Arena", url: "https://olivia-games.github.io/seraph/games/testsubjectarena/index.html", category: "Action", description: "Arena combat as test subject." },
  { name: "Test Subject Complete", url: "https://olivia-games.github.io/seraph/games/testsubjectcomplete/index.html", category: "Action", description: "Complete test subject challenges." },
  { name: "Twinshot", url: "https://olivia-games.github.io/seraph/games/twinshot/index.html", category: "Shooting", description: "Twin stick shooting action." },
  { name: "Twinshot 2", url: "https://olivia-games.github.io/seraph/games/twinshot2/index.html", category: "Shooting", description: "Sequel to Twinshot shooting." },
  { name: "3 Line", url: "https://olivia-games.github.io/seraph/games/3line/index.html", category: "Puzzle", description: "3 line puzzle strategy." },
  { name: "Bike Champ", url: "https://olivia-games.github.io/seraph/games/bikechamp/index.html", category: "Vehicle", description: "Bike racing champion." },
  { name: "Bike Champ 2", url: "https://olivia-games.github.io/seraph/games/bikechamp2/index.html", category: "Vehicle", description: "Sequel to Bike Champ racing." },
  { name: "Corporation Inc.", url: "https://olivia-games.github.io/seraph/games/corporationinc/index.html", category: "Multiplayer", description: "Corporate business simulation." },
  { name: "Shop Empire Fable", url: "https://olivia-games.github.io/seraph/games/shopempirefable/index.html", category: "Multiplayer", description: "Fable-themed shop empire." },
  { name: "Cactus McCoy", url: "https://olivia-games.github.io/seraph/games/cactusmccoy/index.html", category: "Action", description: "Cactus-based action adventure." },
  { name: "Cactus McCoy 2", url: "https://olivia-games.github.io/seraph/games/cactusmccoy2/index.html", category: "Action", description: "Sequel to Cactus McCoy." },
  { name: "Papa Louie", url: "https://olivia-games.github.io/seraph/games/papalouie/index.html", category: "Multiplayer", description: "Papa Louie restaurant management." },
  { name: "Papa Louie 2", url: "https://olivia-games.github.io/seraph/games/papalouie2/index.html", category: "Multiplayer", description: "Second Papa Louie game." },
  { name: "Papa Louie 3", url: "https://olivia-games.github.io/seraph/games/papalouie3/index.html", category: "Multiplayer", description: "Third Papa Louie restaurant game." },
  { name: "Steak and Jake", url: "https://olivia-games.github.io/seraph/games/steakandjake/index.html", category: "Action", description: "Steak and Jake action adventure." },
  { name: "Steak and Jake: Midnight March", url: "https://olivia-games.github.io/seraph/games/steakandjakemidnightmarch/index.html", category: "Action", description: "Midnight March sequel to Steak and Jake." },
];
